"""Gap lane, case goods and fittings: closed hall wardrobes 1.35 m (oak, white), an electric water heater, a flush
ceiling light. Uses the bedroom lane's wardrobe parts and the shared kit, read-only.

blender -b --factory-startup --python catalog/blender/gaps/build_case.py -- [slug ...]
Writes catalog/data/extra/bpy-gaps/<slug>.glb and merges entries.json (shared with build_textiles.py).
"""
import json
import sys
from pathlib import Path

BED = Path(__file__).resolve().parents[1] / "bedroom"
sys.path[:0] = [str(BED.parent), str(BED)]
import kit  # noqa: E402
import parts  # noqa: E402
from parts import BLACK, LACQUER, OAK  # noqa: E402
import pieces as bedroom  # noqa: E402  (bedroom lane, read-only: its wardrobe())

OUT = BED.parents[1] / "data" / "extra" / "bpy-gaps"
TRI_BUDGET = {"wardrobe": 20000, "water_heater": 6000, "lamp": 6000}


def hall_oak():
    bedroom.wardrobe(1.35, 0.6, 2.1, 3, "flat", tint=OAK, spec="oak-rift")


def hall_white():
    bedroom.wardrobe(1.35, 0.6, 2.1, 3, "flat", tint=None, spec=LACQUER, pull="knob")


def water_heater():
    """Slim 50 L wall-hung electric water heater: a flat white tank with rounded edges, a flush grey control strip,
    two pipes underneath. Shallow like a cabinet, so it hangs on any wall. Front -Y, back at y = +d/2."""
    w, d, h = 0.50, 0.28, 0.88
    kit.box((w, d, h), (0, 0, 0.0), "paint:#f2f1ee", bevel=0.05, roughness=0.35, name="tank")
    kit.box((0.30, 0.004, 0.06), (0, -d / 2 - 0.0005, 0.12), "paint:#9a9c9f", bevel=0.002, name="control")
    for x in (-0.08, 0.08):
        kit.cylinder(0.011, 0.10, (x, 0.03, -0.10), "metal:#b7b9bb", verts=16, name="pipe")


def ceiling_light():
    """Flush ceiling light, 35 cm opal dome on a white base; hangs from the ceiling, so its top is at z = 0.12."""
    kit.cylinder(0.15, 0.025, (0, 0, 0.095), "paint:#f4f3f0", verts=64, name="base")
    kit.lathe([(0.0, 0.0), (0.12, 0.012), (0.17, 0.05), (0.175, 0.095)], "paint:#fbfaf6", roughness=0.2, name="dome")


PIECES = {
    "hall-wardrobe-oak-3-door-135": (hall_oak, "wardrobe", "floor", "Rift oak three-door hall wardrobe, flat doors, brass bars, 135x60x210",
                                     ["beige", "brown"], 512000, ["oak-rift", "brass"], "scandinavian"),
    "hall-wardrobe-white-3-door-135": (hall_white, "wardrobe", "floor", "White lacquer three-door hall wardrobe, oak knobs, 135x60x210",
                                       ["white"], 438000, ["lacquered MDF", "oak"], "minimalist"),
    "water-heater-slim-50l": (water_heater, "water_heater", "wall", "Slim electric water heater 50 L, white, wall-hung, 50x28x98 with pipes",
                                  ["white"], 139000, ["enamelled steel"], "modern"),
    "ceiling-light-flush-opal-35": (ceiling_light, "lamp", "ceiling", "Flush ceiling light, opal dome 35 cm, white base",
                                    ["white"], 29000, ["opal glass", "steel"], "modern"),
}


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug, (fn, kind, place, name, colors, price, mats, style) in PIECES.items():
        if args and not any(a in slug for a in args):
            continue
        kit.reset()
        fn()
        parts.bake_modifiers()
        r = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = dict(slug=slug, name=name, kind=kind, placement=place, glb=f"{slug}.glb", size_m=r["size_m"],
                             mesh_extents_m=r["size_m"], colors=colors, price_amd=price, materials=mats, style=style,
                             license="CC0 (generated by varpet)", source_url="generated:bpy", notes="front faces +Z",
                             tags=["generated", "bpy", "gap-fill"], tris=r["tris"], tri_budget=TRI_BUDGET[kind])
        print(f"BUILT {slug} size={r['size_m']} tris={r['tris']} kb={r['bytes'] // 1024}", flush=True)
    manifest.write_text(json.dumps(list(entries.values()), indent=1) + "\n")


main()
