"""Shared by the gap lane's batch builders: one entries.json in catalog/data/extra/bpy-gaps, merged by slug."""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parents[2] / "data" / "extra" / "bpy-gaps"


def record(entries, slug, info, *, name, kind, placement, colors, price, materials, style, budget, batch, tags=(), notes="front faces +Z"):
    entries[slug] = dict(slug=slug, name=name, kind=kind, placement=placement, glb=f"{slug}.glb", size_m=info["size_m"],
                         mesh_extents_m=info["size_m"], colors=colors, price_amd=price, materials=materials, style=style,
                         license="CC0 (generated by varpet)", source_url="generated:bpy", notes=notes,
                         tags=["generated", "bpy", "gap-fill", *tags], tris=info["tris"], tri_budget=budget, batch=batch)
    print(f"BUILT {slug} size={info['size_m']} tris={info['tris']}/{budget}", flush=True)


def load():
    OUT.mkdir(parents=True, exist_ok=True)
    path = OUT / "entries.json"
    return {e["slug"]: e for e in json.loads(path.read_text())} if path.exists() else {}


def save(entries):
    (OUT / "entries.json").write_text(json.dumps(list(entries.values()), indent=1) + "\n")
