"""Build kitchen-fitted-lane pieces headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/kitchen-fitted/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-kitchen-fitted/<slug>.glb + entries.json; deletes the stale preview PNG so
render_previews_studio.py re-renders it.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE), str(HERE.parent)]
import kit  # noqa: E402
import parts  # noqa: E402
import pieces  # noqa: E402
import kit_shapes as ks  # noqa: E402
import bpy  # noqa: E402


def bake():
    for o in kit.meshes():
        if o.modifiers:
            bpy.context.view_layer.objects.active = o
            for x in bpy.context.selected_objects:
                x.select_set(False)
            o.select_set(True)
            for mod in list(o.modifiers):
                try:
                    bpy.ops.object.modifier_apply(modifier=mod.name)
                except RuntimeError:
                    o.modifiers.remove(mod)

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-kitchen-fitted"
PREV = CATALOG / "data" / "previews-extra" / "bpy-kitchen-fitted"


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(pieces.REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = pieces.REGISTRY[slug]
        kit.reset()
        fn()
        bake()
        ks.shrink_images(1024)
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": "floor",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": meta["notes"] + "; front faces +Z", "tags": ["generated", "bpy", *meta["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}", flush=True)
    order = [s for s in pieces.REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
