"""Build dressed beds headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/beds-dressed/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-beds-dressed/<slug>.glb + entries.json; deletes the stale preview PNG.
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE), str(HERE.parent), str(HERE.parent / "soft")]
import kit  # noqa: E402
import kit_shapes as ks  # noqa: E402
import pieces  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-beds-dressed"
PREV = CATALOG / "data" / "previews-extra" / "bpy-beds-dressed"


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(pieces.REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = pieces.REGISTRY[slug]
        kit.reset()
        fn()
        sets = {Path(i.filepath).parent for i in bpy.data.images if i.filepath}
        if sets:  # 512 px is plenty at cushion scale; the procedural linen JPEG alone is ~1.5 MB at 1k
            ks.shrink_images(512)
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": meta["placement"],
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "front faces +Z (foot end); headboard at the back; complete bed with mattress, fitted sheet, duvet, pillows", "tags": ["generated", "bpy", "beds-dressed", *meta["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}", flush=True)
    order = [s for s in pieces.REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
