"""Terrace pieces: one builder per slug plus its manifest metadata. Build with build.py."""
import others as O
import seating as S
from parts import kit

COMMON = {"source_url": "generated:bpy", "license": "CC0 (generated by varpet)", "notes": "Outdoor; front faces +Z",
          "placement": "floor"}
T = ["outdoor", "terrace"]

PIECES = {
    "teak-outdoor-sofa-3seat": (S.teak_sofa, dict(
        name="Teak three-seat outdoor sofa with ecru cushions, terrace, 210 cm", kind="sofa", colors=["beige", "brown"],
        price_amd=690000, materials=["teak", "outdoor fabric"], style="mediterranean",
        tags=T + ["sofa", "three-seat", "cushion", "wood", "loggia"])),
    "modular-outdoor-corner-sofa": (S.corner_sofa, dict(
        name="Modular outdoor corner sofa, anthracite aluminium, grey cushions, 290 x 195 cm", kind="sofa",
        colors=["grey", "black"], price_amd=1450000, materials=["powder-coated aluminium", "outdoor fabric"],
        style="modern minimalist", tags=T + ["sofa", "corner", "modular", "L-shaped", "cushion", "aluminium"])),
    "rope-lounge-armchair": (S.rope_armchair, dict(
        name="Rope lounge armchair with deep cushions, taupe aluminium, outdoor, 76 cm", kind="chair",
        colors=["beige", "brown"], price_amd=320000, materials=["powder-coated aluminium", "polyester rope", "outdoor fabric"],
        style="modern minimalist", tags=T + ["armchair", "lounge", "rope", "cushion"])),
    "teak-sun-lounger": (S.sun_lounger, dict(
        name="Teak sun lounger with adjustable back and wheels, outdoor, 200 cm", kind="chair", colors=["brown"],
        price_amd=380000, materials=["teak", "stainless steel"], style="mediterranean",
        tags=T + ["lounger", "sunbed", "adjustable", "wheels", "wood", "pool"])),
    "teak-dining-table-180": (O.dining_table_180, dict(
        name="Teak outdoor dining table with breadboard ends, seats 6, 180 x 95 cm", kind="table", colors=["brown"],
        price_amd=560000, materials=["teak"], style="mediterranean",
        tags=T + ["dining table", "slatted", "wood", "six-seat"])),
    "teak-dining-armchair": (S.teak_dining_chair, dict(
        name="Teak outdoor dining armchair with seat pad, matches 180 cm table", kind="chair", colors=["brown", "beige"],
        price_amd=145000, materials=["teak", "outdoor fabric"], style="mediterranean",
        tags=T + ["dining chair", "armchair", "slatted", "wood"])),
    "teak-dining-bench-160": (S.teak_bench, dict(
        name="Teak slatted outdoor dining bench, 160 cm", kind="chair", colors=["brown"], price_amd=210000,
        materials=["teak"], style="mediterranean", tags=T + ["bench", "dining", "slatted", "wood"])),
    "teak-concrete-coffee-table": (O.coffee_table, dict(
        name="Outdoor coffee table, concrete top on teak base with slatted shelf, 120 x 70 cm", kind="table",
        colors=["grey", "brown"], price_amd=265000, materials=["fibre concrete", "teak"], style="modern minimalist",
        tags=T + ["coffee table", "concrete", "slatted", "wood"])),
    "gas-fire-table-concrete": (O.gas_fire_table, dict(
        name="Concrete-look gas fire table with lava stones and glass guard, outdoor, 120 x 80 cm", kind="table",
        colors=["grey"], price_amd=720000, materials=["fibre concrete", "stainless steel", "lava stone", "glass"],
        style="modern minimalist", tags=T + ["fire table", "gas", "lounge", "concrete"])),
    "olive-tree-fibreglass-planter": (O.planter_olive, dict(
        name="Olive tree in white fibreglass cylinder planter, outdoor, 230 cm", kind="plant", colors=["green", "white"],
        price_amd=240000, materials=["fibreglass", "live plant"], style="mediterranean",
        tags=T + ["planter", "olive", "tree", "large", "potted"])),
    "terracotta-urn-grasses": (O.urn_grasses, dict(
        name="Terracotta urn with fountain grass, outdoor, 60 cm pot", kind="plant", colors=["orange", "green"],
        price_amd=98000, materials=["terracotta", "live plant"], style="mediterranean",
        tags=T + ["planter", "urn", "grass", "pennisetum", "potted"])),
    "fibreglass-trough-reed-grass": (O.trough_grasses, dict(
        name="Anthracite fibreglass trough planter with feather reed grass, outdoor, 100 cm", kind="plant",
        colors=["green", "grey"], price_amd=135000, materials=["fibreglass", "live plant"], style="modern minimalist",
        tags=T + ["planter", "trough", "grass", "screen", "potted"])),
    "cantilever-parasol-open": (O.parasol_open, dict(
        name="Cantilever parasol 3 x 3 m, open, ecru canopy, weighted cross base", kind="decor", colors=["beige", "grey"],
        price_amd=420000, materials=["powder-coated aluminium", "solution-dyed acrylic", "concrete"], style="mediterranean",
        tags=T + ["parasol", "umbrella", "shade", "cantilever", "open"])),
    "cantilever-parasol-closed": (O.parasol_closed, dict(
        name="Cantilever parasol 3 x 3 m, closed, ecru canopy, weighted cross base", kind="decor", colors=["beige", "grey"],
        price_amd=420000, materials=["powder-coated aluminium", "solution-dyed acrylic", "concrete"], style="mediterranean",
        tags=T + ["parasol", "umbrella", "shade", "cantilever", "closed"])),
    "outdoor-rug-diamond-200x300": (O.rug_200x300, dict(
        name="Sand and charcoal diamond-lattice outdoor rug, flat-weave polypropylene, 200 x 300 cm", kind="rug",
        colors=["beige", "black"], price_amd=115000, materials=["polypropylene"], style="mediterranean",
        tags=T + ["rug", "flat-weave", "weatherproof", "geometric", "large"])),
    "hammock-chair-on-stand": (S.hammock_chair, dict(
        name="Hammock chair on stand, cotton rope sling, black steel C-frame", kind="chair", colors=["beige", "black"],
        price_amd=185000, materials=["cotton rope", "powder-coated steel", "teak"], style="bohemian",
        tags=T + ["hammock chair", "swing", "stand", "lounge", "rope"])),
}
