"""Build wall-lane pieces headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/wall/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-wall/<slug>.glb + entries.json; deletes the stale preview PNG.
Checks that nothing crosses the wall plane (y > 0 before export = glTF z > -d/2).
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE)]
import kit  # noqa: E402
import kit_shapes as ks  # noqa: E402
import pieces  # noqa: E402
import pegboards  # noqa: E402,F401  (registers the pegboard family)

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-wall"
PREV = CATALOG / "data" / "previews-extra" / "bpy-wall"


def bake():
    for o in kit.meshes():
        if o.modifiers:
            bpy.context.view_layer.objects.active = o
            for x in bpy.context.selected_objects:
                x.select_set(False)
            o.select_set(True)
            for mod in list(o.modifiers):
                try:
                    bpy.ops.object.modifier_apply(modifier=mod.name)
                except RuntimeError:
                    o.modifiers.remove(mod)


def max_y():
    bpy.context.view_layer.update()
    return max((o.matrix_world @ v.co).y for o in kit.meshes() for v in o.data.vertices)


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(pieces.REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = pieces.REGISTRY[slug]
        kit.reset()
        fn()
        bake()
        back = max_y()
        sets = {Path(i.filepath).parent for i in bpy.data.images if i.filepath}
        if len(sets) > 2:
            ks.shrink_images(512)
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": "wall",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "Wall-hung; front faces +Z; back flat at z=-d/2",
            "tags": ["generated", "bpy", "wall", *meta["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        flag = "" if back <= 1e-4 else f" BACK-CROSSES-WALL by {back * 1000:.1f} mm"
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}{flag}", flush=True)
    order = [s for s in pieces.REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
