"""Manifest metadata for the balconyplants lane: slug -> (builder, entry fields)."""
import bp_pieces_a as A
import bp_pieces_b as B

COMMON = {"source_url": "generated:bpy", "license": "CC0 (generated by varpet)"}
FLOOR_NOTE = "Outdoor-hardy balcony and loggia planter, stands on the floor; front faces +Z"


def _meta(name, colors, price, materials, style, tags, kind="plant", placement="floor", notes=FLOOR_NOTE):
    return {"name": name, "kind": kind, "colors": colors, "price_amd": price, "materials": materials, "style": style,
            "tags": ["outdoor", "balcony", "loggia", "outdoor-hardy"] + (["plant", "potted"] if kind == "plant" else [])
            + tags, "notes": notes, "placement": placement}


PIECES = {
    "herb-trough-basil-rosemary-thyme-60x20": (A.herb_trough, _meta(
        "Herb trough 60 x 20 cm with basil, rosemary and thyme", ["orange", "green"], 9500,
        ["live plants", "terracotta-look polypropylene"], "mediterranean",
        ["herbs", "basil", "rosemary", "thyme", "trough", "kitchen garden", "edible"])),
    "geranium-pots-trio": (A.geranium_trio, _meta(
        "Zonal geraniums, trio of terracotta pots, red, pink and white", ["red", "pink", "orange", "green"], 14000,
        ["live plants", "terracotta"], "mediterranean",
        ["geranium", "pelargonium", "flowering", "trio", "terracotta", "set of 3"])),
    "lavender-terracotta-pot": (A.lavender_terracotta, _meta(
        "Lavender in a terracotta pot, 34 cm pot", ["purple", "green", "orange"], 12000, ["live plants", "terracotta"],
        "mediterranean", ["lavender", "lavandula", "flowering", "fragrant", "terracotta", "pollinator"])),
    "dwarf-lemon-tree-90": (A.dwarf_lemon, _meta(
        "Dwarf lemon tree, 90 cm, in a cream ceramic pot", ["green", "yellow", "white"], 38000,
        ["live plants", "ceramic"], "mediterranean", ["lemon tree", "citrus", "fruit tree", "meyer lemon", "edible"])),
    "boxwood-ball-square-planter": (A.boxwood_ball, _meta(
        "Boxwood ball topiary in a 40 cm square fibre-cement planter", ["green", "grey"], 42000,
        ["live plants", "fibre cement"], "classic", ["boxwood", "buxus", "topiary", "ball", "evergreen", "square planter"])),
    "zebra-grass-tall-planter": (A.zebra_grass, _meta(
        "Zebra grass (Miscanthus Zebrinus) in a tall square planter, 160 cm", ["green", "yellow", "white"], 32000,
        ["live plants", "fibre cement"], "modern", ["ornamental grass", "miscanthus", "zebra grass", "tall planter",
                                                    "privacy"])),
    "bamboo-galvanised-trough-80": (A.bamboo_trough, _meta(
        "Clumping bamboo (Fargesia) in an 80 cm galvanised trough", ["green", "grey"], 48000,
        ["live plants", "galvanised steel"], "japandi", ["bamboo", "fargesia", "privacy screen", "trough", "clumping",
                                                         "evergreen"])),
    "star-jasmine-trellis-planter-60x30": (B.jasmine_trellis, _meta(
        "Star jasmine on a free-standing trellis planter, 60 x 30 x 150 cm", ["green", "white", "brown"], 55000,
        ["live plants", "teak", "wood"], "mediterranean",
        ["jasmine", "trachelospermum", "climbing", "trellis", "free-standing", "privacy screen", "fragrant"])),
    "tomato-grow-pot-cane": (B.tomato_growpot, _meta(
        "Tomato plant in a fabric grow pot with bamboo cane", ["green", "red", "black"], 8500,
        ["live plants", "felt fabric", "bamboo"], "rustic", ["tomato", "vegetable", "grow bag", "cane", "edible",
                                                             "kitchen garden"])),
    "rose-bush-slate-pot": (B.rose_pot, _meta(
        "Pink patio rose bush in a slate-blue glazed pot", ["pink", "green", "blue"], 18000, ["live plants", "ceramic"],
        "classic", ["rose", "patio rose", "flowering", "shrub"])),
    "succulent-bowl-outdoor-table": (B.succulent_bowl, _meta(
        "Succulent bowl for an outdoor table, 32 cm, sempervivum and echeveria", ["green", "grey", "blue"], 9000,
        ["live plants", "concrete", "gravel"], "modern", ["succulent", "sempervivum", "echeveria", "bowl", "tabletop",
                                                          "centrepiece"],
        placement="surface", notes="Outdoor-hardy succulent bowl for a balcony or garden table; front faces +Z")),
    "tiered-plant-stand-six-pots": (B.tiered_stand, _meta(
        "Three-tier metal and teak plant stand with six small potted plants", ["black", "brown", "green", "orange"],
        34000, ["black steel", "teak", "live plants", "terracotta"], "industrial",
        ["plant stand", "tiered", "etagere", "geranium", "marigold", "petunia", "basil"])),
    "cedar-raised-planter-80x40-planted": (B.cedar_planted, _meta(
        "Cedar raised planter on legs, 80 x 40 cm, with lettuce, chard, chives and strawberries",
        ["brown", "green", "red"], 52000, ["cedar", "wood", "live plants"], "rustic",
        ["raised bed", "raised planter", "vegetable", "kitchen garden", "lettuce", "strawberry", "edible"])),
    "cedar-raised-planter-80x40": (B.cedar_empty, _meta(
        "Cedar raised planter on legs, 80 x 40 cm, empty", ["brown"], 36000, ["cedar", "wood"], "rustic",
        ["raised bed", "raised planter", "planter box", "empty", "kitchen garden"], kind="planter",
        notes="Outdoor cedar planter box, stands on the floor, filled with soil; front faces +Z")),
}
