"""Build the kids' wall-art lane headless and merge its manifest entries.

First draw the artwork:  cd catalog && uv run python blender/kidsart/art.py
Then:  blender -b --factory-startup --python catalog/blender/kidsart/build.py -- [slug ...|all]
Frames and canvases reuse the modern-art lane's parts.py (read-only) with its TEX pointed at kidsart/tex.
Writes catalog/data/extra/bpy-kidsart/<slug>.glb + entries.json; deletes the stale preview PNG.
Checks every back sits on the wall plane (max y == 0 before export = glTF back at z = -d/2).
"""
import json
import math
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE.parent / "modernart"), str(HERE)]
import kit  # noqa: E402
import kspecs  # noqa: E402
import parts  # noqa: E402  (modernart/parts.py)

parts.TEX = HERE / "tex"
CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-kidsart"
PREV = CATALOG / "data" / "previews-extra" / "bpy-kidsart"
FONT_BOARD = "/System/Library/Fonts/Supplemental/Arial.ttf"
FONT_NUM = "/System/Library/Fonts/Supplemental/Arial Rounded Bold.ttf"


def max_y():
    bpy.context.view_layer.update()
    return max((o.matrix_world @ v.co).y for o in kit.meshes() for v in o.data.vertices)


def text_mesh(body, size, x, z, y_back, depth, spec, font, align="CENTER", rough=0.7):
    """Extruded text standing on the wall-facing plane y_back, front toward -Y; (x, z) = anchor point."""
    cu = bpy.data.curves.new("txt", type="FONT")
    cu.body = body
    cu.font = bpy.data.fonts.load(font, check_existing=True)
    cu.size = size
    cu.extrude = depth / 2
    cu.align_x, cu.align_y = align, "CENTER"
    cu.resolution_u = 3
    o = kit._link(bpy.data.objects.new("txt", cu))
    o.rotation_euler = (math.pi / 2, 0, 0)  # text normal +Z -> -Y
    o.location = (x, y_back - depth / 2, z)
    for s in bpy.context.selected_objects:
        s.select_set(False)
    bpy.context.view_layer.objects.active = o
    o.select_set(True)
    bpy.ops.object.convert(target="MESH")
    o = bpy.context.view_layer.objects.active
    bpy.ops.object.transform_apply(location=True, rotation=True, scale=True)
    kit.finish(o, spec, None, rough, 0.0, smooth=False)
    return o


def height_chart(it):
    """Solid oak growth ruler: 1 cm ticks down the left edge, numbers every 10 cm (board bottom = 20 cm)."""
    W, H, D = it["w"], it["h"], 0.018
    kit.box((W, D, H), (0, -D / 2, 0), "oak-rift", bevel=0.002, grain="y", name="board")
    ink, t = "paint:#2f2b28", 0.0006
    x0 = -W / 2
    for cm in range(1, int(H * 100)):
        z = cm / 100
        ln = 0.07 if cm % 10 == 0 else 0.042 if cm % 5 == 0 else 0.025
        th = 0.0026 if cm % 10 == 0 else 0.0016
        kit.box((ln, t, th), (x0 + ln / 2, -D - t / 2, z - th / 2), ink, bevel=0, roughness=0.6, name="tick")
        if cm % 10 == 0:
            text_mesh(str(cm + 20), 0.042, x0 + 0.082, z, -D, t * 1.5, ink, FONT_NUM, align="LEFT", rough=0.6)
    # painted mustard star near the top
    text_mesh("★", 0.05, W * 0.22, H - 0.06, -D, t * 1.5, "paint:#e2b35e", "/System/Library/Fonts/Supplemental/Arial Unicode.ttf",
              rough=0.6)


def felt_board(it, tex):
    parts.frame_item(dict(it, mount="frame"), tex)
    y_felt = -it["depth"] + 0.006
    rows = it["words"]
    pitch = 0.009
    for r, word in enumerate(rows):
        z = it["z"] + (len(rows) / 2 - r - 0.5) * pitch * 6
        text_mesh(word, 0.042, it["x"], z, y_felt, 0.002, "paint:#f4f1ea", FONT_BOARD, rough=0.55)


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = [p["slug"] for p in kspecs.P] if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        p = kspecs.BY_SLUG[slug]
        kit.reset()
        for i, it in enumerate(p["items"]):
            tex = kspecs.tex_name(slug, i)
            {"frame": parts.frame_item, "canvas": parts.canvas_item, "felt": felt_board,
             "height": lambda it, tex: height_chart(it)}[it["mount"]](it, tex)
        back = max_y()
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": p["name"], "kind": "wall_art", "placement": "wall",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": p["colors"], "price_amd": p["price"], "materials": p["materials"],
            "style": p["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "Wall-hung; front faces +Z",
            "tags": ["generated", "bpy", "wall art", "original artwork", p["style"], *p["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        flag = "" if abs(back) <= 1e-4 else f" BACK-OFF-WALL-PLANE {back * 1000:.1f} mm"
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}{flag}", flush=True)
    order = [p["slug"] for p in kspecs.P if p["slug"] in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
