"""Seasonal pieces (New Year, autumn, spring): one builder per slug plus its manifest metadata. Build with build.py."""
import math

from mathutils import Vector

import sz
from sz import Builder, azim, leaf, mat, pp, tube, UP, TAU, GOLD

COMMON = {"source_url": "generated:bpy", "license": "CC0 (generated by varpet)"}
WARM = "#ffc47e"


def rad(d):
    return math.radians(d)


# ================================================================ dressing
BAUBLES = (("sz-bauble-white", "#ece7dc", 0.55, 0.0), ("sz-bauble-champagne", "#cdb07a", 0.3, 1.0),
           ("sz-bauble-smoke", "#6c7c84", 0.18, 0.0), ("sz-bauble-green", "#34473a", 0.35, 0.0))


def spaced(points, n, min_d, rng):
    pts = list(points)
    rng.shuffle(pts)
    out = []
    for p in pts:
        if all((p - q).length >= min_d for q in out):
            out.append(p)
            if len(out) >= n:
                break
    return out


def outer(tr, lo=0.75, hi=1.2, zmin=None, zmax=None):
    out = []
    for p, e in tr.stations + tr.tips:
        r = math.hypot(p.x, p.y)
        if e > 0.02 and lo * e <= r <= hi * e and (zmin is None or p.z >= zmin) and (zmax is None or p.z <= zmax):
            out.append(p)
    return out


def fairy_lights(tr, n, rng, size=None, base_z=0.0):
    size = size or 0.012 * min(1.0, (tr.top - base_z) / 1.4) + 0.002
    E = Builder()
    pts = outer(tr, 0.6, 1.3, zmin=base_z + 0.05)
    for p in spaced(pts, n, 0.05 * (tr.top - base_z) / 1.5, rng):
        r = math.hypot(p.x, p.y)
        q = p + Vector((p.x, p.y, 0)).normalized() * 0.012 if r > 1e-3 else p
        sz.octa(E, q + Vector((0, 0, -0.008)), size)
    E.obj("lights", sz.emit_mat("sz-fairy", WARM, 25.0))


def dress(tr, rng, n_baubles, r0, r1, base_z, n_lights, stars=0):
    groups = [Builder() for _ in BAUBLES]
    caps = Builder()
    pts = outer(tr, 0.85, 1.3, zmin=base_z + 0.2 * (tr.top - base_z), zmax=tr.top - 0.12)
    for i, p in enumerate(spaced(pts, n_baubles, (r1 + r0) * 2.6, rng)):
        k = (i * 7 + rng.randrange(2)) % len(BAUBLES)
        k = 0 if k == 3 and rng.random() < 0.5 else k
        r = rng.uniform(r0, r1) * (1 - 0.3 * (p.z - base_z) / (tr.top - base_z))
        out = Vector((p.x, p.y, 0)).normalized()
        c = p + out * (r * 0.4) + Vector((0, 0, -r - 0.012))
        sz.sphere(groups[k], c, r, 12, 7)
        tube(caps, [c + Vector((0, 0, r * 0.9)), c + Vector((0, 0, r * 1.2))], r * 0.22, sides=6)
        tube(caps, [c + Vector((0, 0, r * 1.2)), p], 0.0008, sides=3, cap_end=False)
    for g, (name, col, rough, metal) in zip(groups, BAUBLES):
        if g.P:
            g.obj(name, sz.plain(name, col, rough, metal))
    if caps.P:
        caps.obj("caps", sz.plain("sz-cap", "#b89a64", 0.35, 1.0))
    if stars:
        S = Builder()
        for p in spaced(outer(tr, 0.8, 1.3, zmin=base_z + 0.2, zmax=tr.top - 0.2), stars, 0.25, rng):
            out = Vector((p.x, p.y, 0)).normalized()
            sz.faceted_star(S, p + out * 0.03 + Vector((0, 0, -0.05)), 0.04, 0.008)
        S.obj("straw-stars", sz.plain("sz-wood-star", "#d9c39a", 0.7))
    fairy_lights(tr, n_lights, rng, base_z=base_z)


def topper(z, R=0.075):
    S = Builder()
    sz.faceted_star(S, (0, 0, z + R * 0.95), R, R * 0.28)
    tube(S, [Vector((0, 0, z - 0.06)), Vector((0, 0, z + 0.02))], 0.006, sides=6)
    S.obj("topper", sz.plain("sz-brass", "#c7a462", 0.28, 1.0))


def fir_tree(slug, height, basket_r, basket_h, tint, n_baubles, n_lights, radius, dressed=True, pot="basket",
             variants=None, whorl_dz=0.1, step=0.05, bauble_r=(0.032, 0.05), stars=6, top_r=0.075, per_whorl=(6, 8)):
    rng = sz.rng_for(slug)
    soil_z, _ = pp.pot(pot, basket_r, basket_h, r_bot=basket_r * 0.84, seed=31, tint=tint)
    C, W = Builder(), Builder()
    base = soil_z - 0.01
    tr = sz.conifer(C, W, base + 0.1 * height, height * 0.9, radius, rng, whorl_dz=whorl_dz, step=step,
                    per_whorl=per_whorl, trunk_r=0.03 * min(1, height / 1.5) + 0.004,
                    card_len=0.14 * min(1, height / 1.5) + 0.03, card_w=0.1 * min(1, height / 1.5) + 0.018)
    tube(W, [Vector((0, 0, base)), Vector((0, 0, base + 0.1 * height + 0.02))], 0.028 * height / 1.8 + 0.01, sides=8)
    W.obj("wood", pp.mat("sz-bark", tex=pp.texture_bark("sz-bark", "#5c4a3a", 4, 0.4), rough=0.9))
    C.obj("needles", sz.needle_mat("sz-fir", variants))
    if dressed:
        dress(tr, rng, n_baubles, bauble_r[0], bauble_r[1], base, n_lights, stars=stars)
        topper(tr.top, top_r)
    return tr


def new_year_tree_180():
    fir_tree("new-year-tree-180", 1.4, 0.25, 0.3, "#b99a68", 42, 240, 0.56)


def new_year_tree_150():
    fir_tree("new-year-tree-150", 1.13, 0.22, 0.26, "#d8d2c6", 32, 190, 0.46)


def potted_fir_120():
    fir_tree("potted-fir-120", 0.92, 0.19, 0.26, "#a8a6a0", 0, 0, 0.42, dressed=False, pot="concrete",
             variants=sz.SPRUCE, whorl_dz=0.075, step=0.036, per_whorl=(7, 9))


def tabletop_fir_60():
    fir_tree("tabletop-fir-60", 0.47, 0.085, 0.11, "#ece8e0", 0, 70, 0.19, pot="ceramic", whorl_dz=0.05,
             step=0.026, stars=0, top_r=0.03, per_whorl=(6, 8))


# ================================================================ shared bits
def wax():
    return sz.plain("sz-wax", "#f2ede3", 0.45)


def lit_candles(specs, kind="pillar"):
    """specs: [(x, y, z, r, h)]. Wax, wicks and flames."""
    Wx, Wk, E = Builder(), Builder(), Builder()
    for x, y, z, r, h in specs:
        (sz.pillar if kind == "pillar" else sz.taper)(Wx, Wk, E, (x, y, z), r, h)
    Wx.obj("wax", wax())
    Wk.obj("wick", sz.plain("sz-wick", "#1b1714", 0.8))
    E.obj("flame", sz.emit_mat("sz-flame", "#ffb45a", 18.0))


def greenery(sprigs, cones, rng, berries=(), card_len=0.11, card_w=0.07):
    """sprigs: [(p, d, length)], cones: [(at, axis, length, r)], berries: [(c, r)]."""
    C, W, K, Bb = Builder(), Builder(), Builder(), Builder()
    for p, d, ln in sprigs:
        sz.sprig(C, W, Vector(p), Vector(d), ln, rng, card_len=card_len, card_w=card_w, step=card_len * 0.42)
    for at, axis, ln, r in cones:
        sz.pine_cone(K, Vector(at), Vector(axis), ln, r, rng)
    for c, r in berries:
        sz.sphere(Bb, c, r, 8, 5)
    C.obj("needles", sz.needle_mat())
    W.obj("twigs", sz.plain("sz-twig", "#5a4631", 0.85))
    if K.P:
        K.obj("cones", mat("sz-cone", tex=sz.gradient_tex("sz-cone", "#3b2718", "#9a7650"), rough=0.85))
    if Bb.P:
        Bb.obj("berries", sz.plain("sz-berry", "#efece4", 0.4))


# ================================================================ Scandi slatted oak tree
def slatted_oak_tree():
    kit = sz.kit
    kit.cylinder(0.19, 0.024, (0, 0, 0), "oak-rift", bevel=0.004, verts=64)
    kit.cylinder(0.012, 1.02, (0, 0, 0.024), "oak-rift", verts=24)
    n = 13
    for i in range(n):
        f = i / (n - 1)
        L = 0.66 * (1 - f) + 0.1
        z = 0.1 + 0.8 * f
        kit.box((L, 0.042, 0.018), (0, 0, z), "oak-rift", bevel=0.005, rot=(0, 0, 90 + i * 19.0))
    S = Builder()
    sz.faceted_star(S, (0, 0, 1.044 + 0.06), 0.07, 0.014)
    S.obj("star", sz.plain("sz-oak-star", "#c9a577", 0.6))


# ================================================================ dried eucalyptus wreath (Wall-hung)
ROUND = lambda s: math.sin(math.pi * min(1.0, 0.04 + s * 0.97)) ** 0.55 + 0.03


def eucalyptus_wreath():
    rng = sz.rng_for("wreath")
    R, zc = 0.21, 0.26
    H = Builder()
    circ = [Vector((R * math.cos(a), 0.0, zc + R * math.sin(a))) for a in [TAU * k / 72 for k in range(73)]]
    tube(H, circ, 0.0035, sides=8, cap_end=False)
    H.obj("hoop", sz.plain("sz-brass", "#c2a064", 0.3, 1.0))
    col, nrm = pp.leaf_texture("sz-euca", [dict(base="#8c9c91", vein="#a0ada3", mid="#a7b1a6"),
                                           dict(base="#a3ada2", vein="#b2bbb0", mid="#b8bfb4")],
                               W=256, TH=128, n_veins=5, vein_amt=0.12, mid_amt=0.35, mottle=0.1, seed=41, nstrength=0.4)
    L, St = Builder(), Builder()
    gather = rad(-105)
    for a0, a1, off in ((gather, rad(150), 0.0), (gather, rad(-25), 0.0), (gather + 0.1, rad(175), 0.008),
                        (gather - 0.1, rad(-45), -0.006), (gather, rad(130), -0.01), (gather, rad(5), 0.01)):
        pts = []
        for k in range(16):
            f = k / 15
            a = a0 + (a1 - a0) * f
            rr = R + off + 0.006 * math.sin(f * 7 + a0)
            pts.append(Vector((rr * math.cos(a), -0.012 - 0.01 * f, zc + rr * math.sin(a))))
        tube(St, pts, lambda t: 0.0028 * (1 - 0.6 * t), sides=5)
        for k in range(1, 26):
            f = k / 26
            p, t = pp.point_on(pts, f)
            radial = Vector((p.x, 0, p.z - zc)).normalized()
            size = (0.036 - 0.02 * f) * rng.uniform(0.85, 1.1)
            for sg in (1, -1):
                d = (t * 0.45 + radial * sg * 0.9 + Vector((0, -rng.uniform(0.15, 0.5), 0))).normalized()
                leaf(L, p, d, size, size * 0.95, ROUND, nu=6, nv=5, bend=rng.uniform(-0.2, 0.3), cup=0.12,
                     up=(0, -1, 0), roll=rng.uniform(-0.4, 0.4), variant=rng.randrange(2), nvar=2)
        leaf(L, pts[-1], (pts[-1] - pts[-2]).normalized() + Vector((0, -0.2, 0)), 0.014, 0.013, ROUND, nu=5, nv=5,
             up=(0, -1, 0), variant=1, nvar=2)
    St.obj("stems", sz.plain("sz-euca-stem", "#6d4b3d", 0.8))
    L.obj("leaves", mat("sz-euca-leaf", tex=col, normal=nrm, nstrength=0.4, rough=0.7))
    # linen bow at the gather and the loop at the top of the hoop
    Bw = Builder()
    g = Vector((R * math.cos(gather), -0.03, zc + R * math.sin(gather)))
    for sg in (1, -1):
        loop = [g + Vector((sg * 0.035 * math.sin(math.pi * k / 10), -0.004 * math.sin(math.pi * k / 10),
                            0.018 * math.sin(2 * math.pi * k / 10))) for k in range(11)]
        tube(Bw, loop, 0.0045, sides=6, cap_end=False)
        tail = [g, g + Vector((sg * 0.02, -0.004, -0.05)), g + Vector((sg * 0.03, -0.002, -0.1))]
        tube(Bw, sz.catmull(tail, 4), 0.0045, sides=6)
    sz.sphere(Bw, g, 0.008, 8, 5)
    top = Vector((0, 0, zc + R))
    tab = [top + Vector((0.01 * math.sin(TAU * k / 12), 0.0, 0.03 * (1 - math.cos(TAU * k / 12)))) for k in range(13)]
    tube(Bw, tab, 0.003, sides=6, cap_end=False)
    Bw.obj("linen", sz.plain("sz-linen", "#d8cebd", 0.9))


# ================================================================ table wreath with candles
def table_wreath_candles():
    rng = sz.rng_for("table-wreath")
    sprigs, cones, berries = [], [], []
    n = 18
    for i in range(n):
        a = TAU * i / n + rng.uniform(-0.1, 0.1)
        rr = 0.165 + rng.uniform(-0.03, 0.03)
        p = Vector((rr * math.cos(a), rr * math.sin(a), 0.012 + rng.uniform(0, 0.02)))
        d = Vector((-math.sin(a), math.cos(a), rng.uniform(0.0, 0.12))) + azim(a, 0) * rng.uniform(-0.35, 0.35)
        sprigs.append((p, d, rng.uniform(0.14, 0.2)))
    for i in range(6):
        a = TAU * i / 6 + 0.3
        rr = 0.17 + rng.uniform(-0.02, 0.02)
        c = Vector((rr * math.cos(a), rr * math.sin(a), 0.028))
        cones.append((c - azim(a + 1.4, 0) * 0.03, azim(a + 1.4, rad(8)), 0.06, 0.02))
    for i in range(9):
        a = TAU * i / 9 + 0.7
        rr = 0.16 + rng.uniform(-0.02, 0.03)
        for j in range(3):
            berries.append(((rr * math.cos(a) + rng.uniform(-0.012, 0.012), rr * math.sin(a) + rng.uniform(-0.012, 0.012),
                             0.05 + rng.uniform(-0.01, 0.012)), 0.006))
    greenery(sprigs, cones, rng, berries)
    Pl = Builder()
    pp.lathe(Pl, [(0, 0), (0.1, 0), (0.105, 0.004), (0.108, 0.012), (0.1, 0.012), (0.095, 0.006), (0, 0.006)], steps=48)
    Pl.obj("plate", sz.plain("sz-stoneware", "#d9d3c8", 0.6))
    lit_candles([(-0.03, 0.02, 0.006, 0.035, 0.15), (0.042, 0.012, 0.006, 0.035, 0.115),
                 (0.0, -0.045, 0.006, 0.035, 0.085)])


# ================================================================ gift boxes
def gift_box(size, at, rotz, paper, ribbon, bow=True, ribbon_w=0.022):
    kit = sz.kit
    before = set(kit.meshes())
    w, d, h = size
    kit.box(size, (0, 0, 0), paper, bevel=0.003)
    t = 0.0025
    kit.box((ribbon_w, d + 2 * t, h + t), (0, 0, 0), ribbon, bevel=0.0)
    kit.box((w + 2 * t, ribbon_w, h + t), (0, 0, 0), ribbon, bevel=0.0)
    if bow:
        Bw = Builder()
        c = Vector((0, 0, h + t))
        for k, ang in enumerate((0.5, 0.5 + math.pi, 1.9, 1.9 + math.pi)):
            ln = 0.055 if k < 2 else 0.042
            dirv = azim(ang, 0)
            loop = [c + dirv * ln * math.sin(math.pi * j / 12) * 1.0 + Vector((0, 0, 0.028 * math.sin(math.pi * j / 12) ** 0.6))
                    + dirv.cross(UP) * 0.012 * math.sin(2 * math.pi * j / 12) for j in range(13)]
            tube(Bw, loop, 0.0055, sides=6, cap_end=False)
        for ang in (0.9, 0.9 + math.pi + 0.5):
            tube(Bw, [c, c + azim(ang, 0) * 0.07 + Vector((0, 0, -0.002))], 0.005, sides=5)
        sz.sphere(Bw, c + Vector((0, 0, 0.006)), 0.011, 8, 5)
        m = sz.kit.material(ribbon)[0]
        Bw.obj("bow", m)
    import mathutils
    M = mathutils.Matrix.Translation(Vector(at)) @ mathutils.Matrix.Rotation(rad(rotz), 4, "Z")
    for o in set(kit.meshes()) - before:
        o.matrix_world = M @ o.matrix_world


def gift_stack():
    rng = sz.rng_for("gifts")
    gift_box((0.4, 0.3, 0.22), (-0.06, 0.0, 0), 4, "paint:#b48c62", "paint:#f1ede4", bow=False)
    gift_box((0.25, 0.21, 0.15), (-0.08, 0.0, 0.2225), -9, "paint:#f0ece4", "paint:#3f5243")
    gift_box((0.28, 0.28, 0.14), (0.28, -0.1, 0), 18, "paint:#8e9d89", "paint:#d8cebd")
    gift_box((0.15, 0.15, 0.2), (0.24, 0.16, 0), -12, "paint:#3b3e40", "paint:#c7a462")
    gift_box((0.14, 0.1, 0.08), (-0.32, -0.21, 0), 28, "paint:#d9ccb4", "paint:#7a2f2a")
    greenery([((-0.12, -0.12, 0.225), (1, 0.15, 0.02), 0.2), ((0.02, -0.1, 0.225), (-1, 0.4, 0.05), 0.16)],
             [((-0.04, -0.1, 0.235), (1, -0.4, 0.05), 0.055, 0.019)], rng)


# ================================================================ table garland with pine cones
def table_garland():
    rng = sz.rng_for("garland")
    L = 1.2
    path = lambda x: Vector((x, 0.035 * math.sin(x * 5.5), 0.0))
    sprigs, cones, berries = [], [], []
    x = -L / 2
    k = 0
    while x < L / 2 - 0.1:
        p = path(x) + Vector((0, rng.uniform(-0.04, 0.04), 0.012 + rng.uniform(0, 0.03)))
        dirx = 1 if k % 2 == 0 else -1
        start = p if dirx > 0 else p + Vector((0.18, 0, 0))
        d = Vector((dirx, rng.uniform(-0.45, 0.45), rng.uniform(0.02, 0.15)))
        sprigs.append((start, d, rng.uniform(0.18, 0.26)))
        x += 0.06
        k += 1
    for i in range(9):
        xx = -L / 2 + 0.08 + (L - 0.16) * i / 8 + rng.uniform(-0.03, 0.03)
        c = path(xx) + Vector((0, rng.uniform(-0.05, 0.05), 0.024))
        a = rng.uniform(0, TAU)
        cones.append((c - azim(a, 0) * 0.035, azim(a, rad(rng.uniform(5, 20))), rng.uniform(0.06, 0.08), 0.022))
    for i in range(14):
        xx = -L / 2 + 0.05 + (L - 0.1) * rng.random()
        c = path(xx) + Vector((0, rng.uniform(-0.06, 0.06), 0.06 + rng.uniform(-0.01, 0.02)))
        berries.append((c, 0.006))
    greenery(sprigs, cones, rng, berries)
    E, Wr = Builder(), Builder()
    wire = [path(-L / 2 + L * i / 60) + Vector((0, 0.03 * math.sin(i * 1.3), 0.055 + 0.015 * math.sin(i * 0.9)))
            for i in range(61)]
    tube(Wr, wire, 0.0012, sides=3, cap_end=False)
    for i in range(1, 60, 2):
        sz.octa(E, wire[i] + Vector((0, 0, 0.004)), 0.007)
    Wr.obj("wire", sz.plain("sz-wire", "#8a6a3c", 0.4, 1.0))
    E.obj("lights", sz.emit_mat("sz-fairy", WARM, 25.0))


# ================================================================ lantern with candle and pine
def lantern_pine():
    rng = sz.rng_for("lantern")
    kit = sz.kit
    blk = "paint:#1d1d1d"
    s, h = 0.2, 0.34
    kit.box((s + 0.02, s + 0.02, 0.022), (0, 0, 0), blk, bevel=0.003)
    for x in (-1, 1):
        for y in (-1, 1):
            kit.box((0.012, 0.012, h), (x * s / 2, y * s / 2, 0.022), blk, bevel=0.001)
    kit.box((s + 0.016, s + 0.016, 0.016), (0, 0, 0.022 + h), blk, bevel=0.002)
    for x, y, sx, sy in ((0, -1, s - 0.012, 0.003), (0, 1, s - 0.012, 0.003), (-1, 0, 0.003, s - 0.012), (1, 0, 0.003, s - 0.012)):
        kit.box((sx, sy, h - 0.004), (x * s / 2, y * s / 2, 0.024), "glass", bevel=0.0)
    R = Builder()
    z0 = 0.022 + h + 0.016
    a = (s + 0.016) / 2
    apex = Vector((0, 0, z0 + 0.075))
    corners = [Vector((sx * a, sy * a, z0)) for sx, sy in ((-1, -1), (1, -1), (1, 1), (-1, 1))]
    for i in range(4):
        p0, p1 = corners[i], corners[(i + 1) % 4]
        i0, i1, i2 = R.add(p0), R.add(p1), R.add(apex)
        R.F.append((i0, i1, i2))
    tube(R, [apex, apex + Vector((0, 0, 0.02))], 0.012, sides=12)
    ring = [apex + Vector((0, 0.0, 0.02)) + Vector((0.022 * math.sin(TAU * k / 32), 0, 0.022 * (1 - math.cos(TAU * k / 32)) ))
            for k in range(33)]
    tube(R, ring, 0.004, sides=8, cap_end=False)
    R.obj("roof", kit.material(blk)[0])
    lit_candles([(0, 0, 0.022, 0.042, 0.14)])
    sprigs = [((-0.2, -0.14, 0.01), (1, 0.1, 0.02), 0.2), ((0.18, -0.13, 0.01), (-0.6, 1, 0.03), 0.18),
              ((0.14, 0.16, 0.01), (-1, 0.1, 0.03), 0.2), ((-0.16, 0.14, 0.012), (0.3, -1, 0.02), 0.16),
              ((-0.05, -0.17, 0.02), (1, 0.4, 0.06), 0.14)]
    cones = [((-0.02, -0.19, 0.022), (1, 0.2, 0), 0.07, 0.022), ((0.16, -0.05, 0.022), (0.3, -1, 0), 0.065, 0.021),
             ((-0.17, 0.02, 0.022), (-0.2, 1, 0.1), 0.06, 0.02)]
    greenery(sprigs, cones, rng)


# ================================================================ ceramic star lights
def ceramic_star_lights():
    kit = sz.kit
    S, D, Pg = Builder(), Builder(), Builder()
    for x, y, R in ((-0.13, 0.02, 0.105), (0.05, -0.02, 0.08), (0.18, 0.04, 0.058)):
        bw = R * 0.8
        kit.box((bw, 0.05, 0.028), (x, y, 0), "oak-rift", bevel=0.004)
        cz = 0.028 + 0.012 + R * 0.809
        dots = []
        sz.faceted_star(S, (x, y, cz), R, R * 0.26, dots=dots)
        tube(Pg, [Vector((x, y, 0.02)), Vector((x, y, 0.028 + 0.012 + R * 0.3))], 0.003, sides=6)
        for p in dots:
            sz.octa(D, p + Vector((0, -0.0015, 0)), 0.0032)
    S.obj("porcelain", sz.emit_mat("sz-porcelain", "#f3efe7", 0.6))
    D.obj("pierced", sz.emit_mat("sz-glow", WARM, 30.0))
    Pg.obj("peg", sz.plain("sz-brass", "#c2a064", 0.3, 1.0))


# ================================================================ advent candle set
def advent_candles():
    rng = sz.rng_for("advent")
    kit = sz.kit
    kit.box((0.46, 0.13, 0.012), (0, 0, 0), "oak-rift", bevel=0.002)
    for y in (-1, 1):
        kit.box((0.46, 0.012, 0.03), (0, y * 0.059, 0), "oak-rift", bevel=0.003)
    for x in (-1, 1):
        kit.box((0.012, 0.106, 0.03), (x * 0.224, 0, 0), "oak-rift", bevel=0.003)
    xs = (-0.165, -0.055, 0.055, 0.165)
    lit_candles([(x, 0, 0.012, 0.033, h) for x, h in zip(xs, (0.075, 0.09, 0.105, 0.12))])
    sprigs, cones, berries = [], [], []
    for i, x in enumerate((-0.21, -0.11, 0.0, 0.11)):
        sprigs.append(((x, -0.045 + 0.01 * (i % 2), 0.018), (1, 0.35 * (-1) ** i, 0.08), 0.12))
        sprigs.append(((x + 0.1, 0.045, 0.018), (-1, -0.3 * (-1) ** i, 0.08), 0.1))
    for x in (-0.11, 0.0, 0.11):
        cones.append(((x - 0.02, 0.035, 0.03), (1, -0.3, 0.1), 0.045, 0.016))
        berries.append(((x + 0.01, -0.04, 0.035), 0.006))
        berries.append(((x + 0.02, -0.03, 0.04), 0.005))
    greenery(sprigs, cones, rng, berries, card_len=0.08, card_w=0.05)


# ================================================================ pumpkins
def pumpkin_trio():
    rng = sz.rng_for("pumpkins")
    stems = Builder()
    for name, (x, y, R, H, lobes, col, squash) in {
            "white": (-0.08, 0.02, 0.13, 0.16, 10, "#e8e1d2", 1.0),
            "sage": (0.14, 0.05, 0.1, 0.1, 12, "#94a39a", 0.95),
            "amber": (0.06, -0.14, 0.075, 0.085, 9, "#d8995a", 1.0)}.items():
        B = Builder()
        sz.pumpkin(B, (x, y, 0), R, H, lobes, 0.08, squash, rng)
        tex = pp.texture_speckle("sz-pk-" + name, col, seed=len(name), amt=0.07, dots=0.0)
        B.obj("pumpkin-" + name, mat("sz-pk-" + name, tex=tex, rough=0.55))
        top = Vector((x, y, H * 0.84))
        a = rng.uniform(0, TAU)
        pts = sz.catmull([top, top + Vector((0, 0, 0.03)), top + Vector((0, 0, 0.05)) + azim(a, 0) * 0.02,
                          top + Vector((0, 0, 0.055)) + azim(a, 0) * 0.04], 4)
        tube(stems, pts, lambda t: (0.013 + R * 0.05) * (1 - 0.35 * t), sides=7, jitter=0.25, rng=rng)
    stems.obj("stems", sz.plain("sz-pk-stem", "#6e5a3e", 0.85))


# ================================================================ tulips in glass vase
PETAL = lambda s: math.sin(math.pi * min(1.0, 0.1 + s * 0.92)) ** 0.5 * (0.85 + 0.15 * s)


def tulip_vase():
    rng = sz.rng_for("tulips")
    V = Builder()
    prof = [(0.0, 0.0), (0.05, 0.0), (0.056, 0.004), (0.056, 0.23), (0.052, 0.232), (0.051, 0.23),
            (0.051, 0.016), (0.0, 0.016)]
    pp.lathe(V, prof, steps=48)
    V.obj("vase", sz.kit.material("glass")[0])
    Wt = Builder()
    pp.lathe(Wt, [(0.0, 0.016), (0.05, 0.016), (0.05, 0.14), (0.0, 0.14)], steps=36)
    Wt.obj("water", sz.kit.material("glass")[0])
    ptex, pnrm = pp.leaf_texture("sz-petal", [dict(base="#f2c6cc", vein="#e7aeb7", mid="#dc9ba6"),
                                              dict(base="#f4ece0", vein="#ecdcc8", mid="#e3cfb4")],
                                 W=256, TH=128, n_veins=14, vein_k=0.1, vein_amt=0.15, mid_amt=0.2, mottle=0.05,
                                 seed=51, nstrength=0.4)
    ltex, lnrm = pp.leaf_texture("sz-tulip-leaf", [dict(base="#6b8a5e", vein="#7c9a6e", mid="#8aa67b")],
                                 W=256, TH=64, n_veins=1, vein_amt=0.0, mid_amt=0.3, mottle=0.08, seed=52, nstrength=0.3)
    St, Pt, Lf = Builder(), Builder(), Builder()
    n = 9
    for i in range(n):
        a = i * GOLD
        spread = 0.04 + 0.1 * (i / n) ** 0.7
        base = Vector((0.018 * math.cos(a), 0.018 * math.sin(a), 0.02))
        lip = Vector((0.03 * math.cos(a), 0.03 * math.sin(a), 0.23))
        hz = rng.uniform(0.36, 0.44) - 0.04 * (i / n)
        head = Vector((spread * math.cos(a), spread * math.sin(a), hz))
        droop = Vector((0, 0, -0.02 * (i / n)))
        pts = sz.catmull([base, lip, (lip + head) / 2 + azim(a, 0) * 0.01, head + droop], 5)
        tube(St, pts, 0.0035, sides=6, cap_end=False)
        axis = (pts[-1] - pts[-3]).normalized()
        T = Builder()
        var = 0 if i % 3 else 1
        for k in range(6):
            pa = k * TAU / 6 + (0.5 if k % 2 else 0)
            rad_v = azim(pa, 0)
            ln = 0.052 if k % 2 == 0 else 0.048
            r0 = 0.004 if k % 2 == 0 else 0.007
            d = (UP + rad_v * 0.28).normalized()
            leaf(T, rad_v * r0, d, ln, 0.038, PETAL, nu=8, nv=5, bend=-0.45, cup=0.35, up=rad_v, variant=var, nvar=2,
                 thick=0.08)
        sz.merge(Pt, T, sz.frame_to(axis, pts[-1]))
        if i % 2 == 0:
            lb = Vector((0.03 * math.cos(a + 0.4), 0.03 * math.sin(a + 0.4), 0.2))
            leaf(Lf, lb, azim(a + 0.4, rad(62)), 0.2, 0.034, lambda s: math.sin(math.pi * min(1, 0.15 + s)) ** 0.5,
                 nu=10, nv=3, bend=1.1, fold=0.3, twist=0.5, variant=0, nvar=1)
    St.obj("stems", sz.plain("sz-tulip-stem", "#6f8e57", 0.5))
    Pt.obj("petals", mat("sz-petal", tex=ptex, normal=pnrm, nstrength=0.3, rough=0.45))
    Lf.obj("leaves", mat("sz-tulip-leaf", tex=ltex, normal=lnrm, nstrength=0.3, rough=0.5))


# ================================================================ manifest
def _meta(name, kind, colors, price, materials, style, tags, placement, notes="front faces +Z"):
    return {"name": name, "kind": kind, "colors": colors, "price_amd": price, "materials": materials, "style": style,
            "tags": ["seasonal"] + tags, "notes": notes, "placement": placement}


NY = ["new year", "christmas", "winter", "holiday", "festive"]
PIECES = {
    "new-year-tree-180": (new_year_tree_180, _meta(
        "Dressed New Year fir tree, 180 cm, in woven seagrass basket", "plant", ["green", "white", "yellow"], 68000,
        ["artificial foliage", "seagrass", "glass", "brass"], "scandinavian",
        NY + ["tree", "fir", "fairy lights", "baubles", "large"], "floor",
        "Floor plant; warm emissive fairy lights, baubles in white, champagne, smoke and forest green; front faces +Z")),
    "new-year-tree-150": (new_year_tree_150, _meta(
        "Dressed New Year fir tree, 150 cm, in pale woven basket", "plant", ["green", "white", "yellow"], 52000,
        ["artificial foliage", "seagrass", "glass", "brass"], "scandinavian",
        NY + ["tree", "fir", "fairy lights", "baubles"], "floor",
        "Floor plant; warm emissive fairy lights, restrained bauble palette; front faces +Z")),
    "potted-fir-120": (potted_fir_120, _meta(
        "Potted blue spruce, 120 cm, undecorated, in concrete pot", "plant", ["green", "grey"], 34000,
        ["artificial foliage", "concrete"], "scandinavian",
        NY + ["tree", "spruce", "pine", "conifer", "undecorated"], "floor",
        "Floor plant; undecorated, dress it yourself; front faces +Z")),
    "tabletop-fir-60": (tabletop_fir_60, _meta(
        "Tabletop fir, 60 cm, with warm fairy lights, in cream ceramic pot", "plant", ["green", "white"], 16000,
        ["artificial foliage", "ceramic"], "scandinavian", NY + ["tree", "fir", "fairy lights", "small", "tabletop"],
        "surface", "Tabletop plant; warm emissive fairy lights; front faces +Z")),
    "slatted-oak-new-year-tree-120": (slatted_oak_tree, _meta(
        "Scandi slatted oak New Year tree, 120 cm", "decor", ["beige", "brown"], 38000, ["oak"], "scandinavian",
        NY + ["wooden tree", "slatted", "alternative tree", "minimal"], "floor",
        "Oak slats spiral round a dowel on a round base, oak star on top; front faces +Z")),
    "dried-eucalyptus-wreath-45": (eucalyptus_wreath, _meta(
        "Dried eucalyptus wreath on brass hoop, 45 cm, with linen bow", "wall_hanging", ["green", "grey", "yellow"],
        19000, ["dried eucalyptus", "brass", "linen"], "scandinavian",
        NY + ["wreath", "eucalyptus", "dried flowers", "door", "hoop"], "wall",
        "Wall-hung; front faces +Z; back flat at z=-d/2")),
    "table-wreath-three-candles": (table_wreath_candles, _meta(
        "Fir table wreath centrepiece with pine cones and three lit pillar candles", "candle",
        ["green", "white", "brown"], 21000, ["artificial foliage", "pine cones", "wax", "stoneware"], "scandinavian",
        NY + ["wreath", "centrepiece", "table", "candles", "pine cones"], "surface",
        "Table centrepiece; flames are emissive; front faces +Z")),
    "gift-box-stack": (gift_stack, _meta(
        "Stack of five wrapped gift boxes with ribbons and a fir sprig", "decor",
        ["brown", "white", "green", "grey"], 14000, ["paper", "cotton ribbon", "artificial foliage"], "scandinavian",
        NY + ["gifts", "presents", "under the tree", "wrapped"], "floor",
        "Group of boxes for under a tree; front faces +Z")),
    "pine-cone-table-garland-120": (table_garland, _meta(
        "Fir table garland, 120 cm, with pine cones, white berries and warm micro lights", "decor",
        ["green", "brown", "white"], 17000, ["artificial foliage", "pine cones", "copper wire"], "scandinavian",
        NY + ["garland", "table runner", "mantel", "pine cones", "fairy lights"], "surface",
        "Lies flat along a table or mantelpiece, runs along X; lights are emissive; front faces +Z")),
    "black-lantern-candle-pine": (lantern_pine, _meta(
        "Black metal lantern with lit pillar candle, fir sprigs and pine cones", "lantern",
        ["black", "green", "white"], 23000, ["powder-coated steel", "glass", "wax", "artificial foliage"],
        "scandinavian", NY + ["lantern", "candle", "pine cones", "hurricane"], "surface",
        "Glass is alpha-blended with transmission; flame is emissive; front faces +Z")),
    "ceramic-star-lights-trio": (ceramic_star_lights, _meta(
        "Trio of pierced porcelain star lights on oak blocks", "decor", ["white", "beige"], 15000,
        ["porcelain", "oak", "brass"], "scandinavian", NY + ["star", "lights", "porcelain", "night light", "set"],
        "surface", "Warm glow through pierced dots is emissive; front faces +Z")),
    "advent-candle-tray-oak": (advent_candles, _meta(
        "Advent candle set: four lit pillars in an oak tray with fir and pine cones", "candle",
        ["white", "beige", "green"], 18000, ["oak", "wax", "artificial foliage", "pine cones"], "scandinavian",
        NY + ["advent", "candles", "tray", "centrepiece"], "surface",
        "Candles burned down in advent order; flames are emissive; front faces +Z")),
    "autumn-pumpkin-trio": (pumpkin_trio, _meta(
        "Autumn pumpkin trio in white, sage and amber", "decor", ["white", "green", "orange"], 9000,
        ["ceramic"], "scandinavian", ["autumn", "harvest", "pumpkin", "gourd", "set"], "surface",
        "Tabletop group; front faces +Z")),
    "spring-tulips-glass-vase": (tulip_vase, _meta(
        "Spring tulip bouquet, pink and cream, in clear glass vase", "decor", ["pink", "white", "green"], 12000,
        ["artificial flowers", "glass"], "scandinavian", ["spring", "tulips", "flowers", "bouquet", "vase", "easter"],
        "surface", "Glass is alpha-blended with transmission; front faces +Z")),
}
