import type { SceneDocument, Vec2, Wall } from '../contracts';
import { normalizeWallJunctions } from './wall-junctions';
import { analyzeProject, emptyProject, projectSnapshot } from './renovation';
import { componentPosition, componentRotation } from './geometry';
import { validateScene } from './validation';

let assertions = 0;
function assert(condition: unknown, message: string): asserts condition { assertions++; if (!condition) throw new Error(message); }
function near(actual: number, expected: number, message: string): void { assert(Math.abs(actual - expected) < 1e-8, message); }
function throws(action: () => unknown, pattern: RegExp, message: string): void { let error: unknown; try { action(); } catch (caught) { error = caught; } assert(error instanceof Error && pattern.test(error.message), message); }
const json = (value: unknown) => JSON.stringify(value);
const wall = (id: string, start: Vec2, end: Vec2): Wall => ({ id, start, end, height: 2.7, thickness: .16, color: '#eeeeee', openings: [] });
function scene(walls: Wall[]): SceneDocument {
  return { format: 'varpet.editor', version: 1, id: 'junction-check', name: 'Junction check', units: 'm', upAxis: 'Y', rooms: [{ id: 'room', name: 'Room', polygon: [[-10,-10],[10,-10],[10,10],[-10,10]], color: '#ffffff' }], walls, objects: [] };
}
const tee = scene([wall('long', [0,0], [8,0]), wall('divider', [3,0], [3,3])]);
const split = normalizeWallJunctions(tee);
assert(split.walls.length === 3, 'T junction must divide the long selectable wall into two walls');
assert(split.walls.find(w => w.id === 'long')!.end[0] === 3, 'first section keeps the source wall identity');
assert(tee.walls.length === 2 && tee.walls[0]!.end[0] === 8, 'normalization never mutates the supplied document');
assert(split.version === 1 && !split.project, 'v1 geometry normalization retains the v1 boundary');
assert(json(normalizeWallJunctions(split)) === json(split), 'normalization is idempotent, including section IDs');
assert(validateScene(split, []).ok, 'normalized tee remains a valid document');
const cross = normalizeWallJunctions(scene([wall('a', [-2,0], [2,0]), wall('b', [0,-2], [0,2])]));
assert(cross.walls.length === 4, 'X intersection creates four independently selectable walls');
const diagonal = normalizeWallJunctions(scene([wall('a', [0,0], [6,6]), wall('b', [0,6], [6,0])]));
assert(diagonal.walls.length === 4 && diagonal.walls.every(w => w.start[0] === 3 || w.end[0] === 3), 'diagonal crossings split at their true intersection');
const many = normalizeWallJunctions(scene([wall('a', [0,0], [8,0]), wall('b', [2,0], [2,3]), wall('c', [5,-2], [5,2])]));
assert(many.walls.length === 6, 'multiple T and X intersections split each interval once');
assert(many.walls.filter(w => w.start[1] === 0 && w.end[1] === 0).map(w => w.end[0] - w.start[0]).join(',') === '2,3,3', 'multiple cuts retain order and exact total length');
const corners = scene([wall('a', [0,0], [2,0]), wall('b', [2,0], [2,2]), wall('c', [0,1], [1,1]), wall('d', [2,0], [4,0])]);
assert(json(normalizeWallJunctions(corners)) === json(corners), 'corners, parallel walls and manual collinear endpoints remain distinct');
const nearMiss = scene([wall('a', [0,0], [4,0]), wall('b', [2,.001], [2,2])]);
assert(normalizeWallJunctions(nearMiss).walls.length === 2, 'nearby wall endpoints are not silently snapped into junctions');
const fractional = normalizeWallJunctions(scene([wall('a', [.6,-4], [.6,4]), wall('divider', [-5,.4], [.6,.4])]));
assert(fractional.walls[0]!.end[1] === .4, 'T junction reuses the exact existing fractional endpoint');
const oldCorner = scene([wall('left', [0,0], [3,0]), wall('right', [3,0], [3,3])]);
const flattened = structuredClone(oldCorner); flattened.walls[1]!.end = [6,0];
assert(normalizeWallJunctions(flattened, oldCorner).walls.length === 2, 'straightening an ordinary corner does not pretend a third divider was removed');

const levels = structuredClone(tee); levels.version = 2; levels.project = emptyProject();
levels.project.metadata.divider = { elevation: 3 };
assert(normalizeWallJunctions(levels).walls.length === 2, 'walls on different storeys do not create plan junctions');
levels.project.metadata.divider = { elevation: 2.7 };
assert(normalizeWallJunctions(levels).walls.length === 2, 'vertical spans merely touching do not split');
levels.project.metadata.divider = { elevation: 2.6 };
assert(normalizeWallJunctions(levels).walls.length === 3, 'overlapping raised partitions do split');
levels.project.metadata.divider = { phase: 'remove' };
assert(normalizeWallJunctions(levels).walls.length === 2, 'walls marked for removal do not divide active walls');

const furnished = structuredClone(tee); furnished.version = 2; furnished.project = emptyProject();
const project = furnished.project;
project.mode = 'renovate';
project.metadata.long = { name: 'Main wall', phase: 'existing', locked: true, review: 'reviewed', structuralRole: 'partition' };
furnished.walls[0]!.openings = [{ id: 'window', kind: 'window', offset: 5, width: 1, sill: 1, height: 1 }];
project.components = [{ id: 'mounted', kind: 'cabinet', name: 'Mounted cabinet', color: '#ffffff', phase: 'existing', dimensions: [.5,.5,.2], position: [0,0,0], rotation: .2, host: { wallId: 'long', offset: 6.5, elevation: 1, side: -1 } }];
project.materials = [{ id: 'paint', name: 'Paint', unit: 'm2', unitCost: 5, wastePercent: 10, thickness: .001, color: '#ffddcc' }];
project.finishes = [{ id: 'front', entityId: 'long', materialId: 'paint', surface: 'wall-front' }];
project.assumptions = [{ id: 'proof', entityId: 'long', property: 'length', value: '8 m', status: 'accepted', sourceKind: 'inferred', sourceIds: [], rationale: 'Recorded before segmentation', alternatives: [] }, { id: 'dependent', entityId: 'room', property: 'boundary', value: 'Checked', status: 'accepted', sourceKind: 'inferred', sourceIds: [], rationale: 'Wall dependency', alternatives: [], dependsOn: ['long'] }];
project.tasks = [{ id: 'task', title: 'Paint wall', trade: 'Paint', status: 'todo', entityIds: ['long'], dependsOn: [], allowance: 0 }];
const originalPosition = componentPosition(furnished, project.components[0]!);
const originalRotation = componentRotation(furnished, project.components[0]!);
const cost = analyzeProject(furnished, []).totalCost;
const furnishedSplit = normalizeWallJunctions(furnished);
const second = furnishedSplit.walls.find(w => w.start[0] === 3 && w.end[0] === 8)!;
assert(second.openings[0]!.id === 'window' && second.openings[0]!.offset === 2, 'opening identity and world placement survive splitting');
assert(json(componentPosition(furnishedSplit, furnishedSplit.project!.components[0]!)) === json(originalPosition), 'mounted component stays in the same world position');
near(componentRotation(furnishedSplit, furnishedSplit.project!.components[0]!), originalRotation, 'mounted component keeps its world rotation');
assert(furnishedSplit.project!.components[0]!.host!.wallId === second.id, 'mounted component is hosted by its selected section');
assert(json(furnishedSplit.project!.metadata[second.id]) === json(project.metadata.long), 'split retains locks, review state and existing renovation phase');
near(analyzeProject(furnishedSplit, []).totalCost, cost, 'splitting conserves finish area and price');
assert(furnishedSplit.project!.finishes.length === 2, 'both sections inherit the existing surface coating');
assert(furnishedSplit.project!.tasks[0]!.entityIds.includes(second.id), 'work packages continue to cover both wall sections');
assert(furnishedSplit.project!.assumptions.some(a => a.entityId === second.id && a.property === 'length' && a.status === 'stale'), 'wall evidence follows both sections without misrepresenting the old full-wall measurement');
assert(furnishedSplit.project!.assumptions.find(a => a.id === 'dependent')!.dependsOn!.includes(second.id), 'dependent evidence continues to cover the complete original wall');
assert(validateScene(furnishedSplit, []).ok, 'split metadata and references form a valid document');
const withSnapshots = structuredClone(furnished);
withSnapshots.project!.baseline = projectSnapshot(withSnapshots);
withSnapshots.project!.options = [{ id: 'saved-option', name: 'Saved option', snapshot: projectSnapshot(withSnapshots) }];
const normalizedSnapshots = normalizeWallJunctions(withSnapshots);
assert(normalizedSnapshots.project!.baseline!.walls.length === 3, 'baseline geometry is normalized before section references can depend on it');
assert(json(normalizedSnapshots.project!.baseline!.walls.map(w => w.id)) === json(normalizedSnapshots.walls.map(w => w.id)), 'identical geometry reuses section identity across baseline and active state');
assert(json(normalizedSnapshots.project!.options[0]!.snapshot.walls.map(w => w.id)) === json(normalizedSnapshots.walls.map(w => w.id)), 'identical option geometry shares the same section identities');
assert(json(normalizeWallJunctions(normalizedSnapshots)) === json(normalizedSnapshots), 'normalizing all saved geometry remains idempotent');
const restored = structuredClone(normalizedSnapshots), savedBaseline = restored.project!.baseline!;
restored.rooms = savedBaseline.rooms; restored.walls = savedBaseline.walls; restored.objects = savedBaseline.objects;
Object.assign(restored.project!, { metadata: savedBaseline.metadata, components: savedBaseline.components, routes: savedBaseline.routes, finishes: savedBaseline.finishes });
assert(validateScene(restored, []).ok, 'restoring the baseline preserves valid shared evidence and work-package references before normalization');
const differentSnapshot = structuredClone(withSnapshots);
differentSnapshot.project!.baseline!.walls.find(w => w.id === 'divider')!.start[0] = 4;
differentSnapshot.project!.baseline!.walls.find(w => w.id === 'divider')!.end[0] = 4;
const differentNormalized = normalizeWallJunctions(differentSnapshot);
const activeSecond = differentNormalized.walls.find(w => w.start[0] === 3 && w.end[0] === 8)!;
const baselineSecond = differentNormalized.project!.baseline!.walls.find(w => w.start[0] === 4 && w.end[0] === 8)!;
assert(activeSecond.id !== baselineSecond.id, 'different section geometry never silently reuses another saved section identity');
assert(validateScene(differentNormalized, []).ok, 'shared evidence remains valid with differing snapshot junctions');
const snapshotSecond = normalizedSnapshots.walls.find(w => w.start[0] === 3 && w.end[0] === 8)!;
const snapshotJoin = normalizeWallJunctions(withoutDivider(normalizedSnapshots), normalizedSnapshots);
assert(snapshotJoin.project!.assumptions.some(a => a.entityId === snapshotSecond.id), 'joining active sections preserves evidence attached to a section in a saved snapshot');
assert(snapshotJoin.project!.tasks[0]!.entityIds.includes(snapshotSecond.id) && snapshotJoin.project!.tasks[0]!.entityIds.includes('long'), 'work packages retain both saved-section and joined-active coverage');
assert(validateScene(snapshotJoin, []).ok, 'snapshot-aware merge references remain valid');
const recolored = structuredClone(furnishedSplit); recolored.walls.find(w => w.id === second.id)!.color = '#112233';
assert(recolored.walls.find(w => w.id === 'long')!.color === '#eeeeee', 'independent section edits do not leak to adjacent walls');

function withoutDivider(input: SceneDocument): SceneDocument { const result = structuredClone(input); result.walls = result.walls.filter(w => w.id !== 'divider'); if (result.project) delete result.project.metadata.divider; return result; }
const joined = normalizeWallJunctions(withoutDivider(split), split);
assert(joined.walls.length === 1 && joined.walls[0]!.id === 'long' && joined.walls[0]!.end[0] === 8, 'removing the divider reconnects sections under the original identity');
assert(json(normalizeWallJunctions(joined, split)) === json(joined), 'reconnection is idempotent');
const sameLayoutOtherDocument = withoutDivider(split); sameLayoutOtherDocument.id = 'unrelated-import';
assert(normalizeWallJunctions(sameLayoutOtherDocument, split).walls.length === 2, 'unrelated imports retain their own deliberate collinear split');
const stillSplit = normalizeWallJunctions(split, split);
assert(stillSplit.walls.length === 3, 'an existing divider prevents reconnection');
const readded = structuredClone(joined); readded.walls.push(structuredClone(tee.walls[1]!));
assert(normalizeWallJunctions(readded, joined).walls.length === 3, 'adding the divider again creates separate sections again');
const removed = structuredClone(furnishedSplit); removed.project!.metadata.divider = { phase: 'remove' };
const removalJoined = normalizeWallJunctions(removed, furnishedSplit);
assert(removalJoined.walls.length === 2, 'renovation removal reconnects active sections while retaining demolition geometry');
assert(removalJoined.project!.finishes.length === 1, 'reconnection deduplicates identical finish coverage');
near(analyzeProject(removalJoined, []).totalCost, cost, 'reconnection preserves coating cost');
assert(json(componentPosition(removalJoined, removalJoined.project!.components[0]!)) === json(originalPosition), 'reconnection preserves hosted position');
assert(removalJoined.project!.tasks[0]!.entityIds.join(',') === 'long', 'joined work-package references use the retained identity once');
assert(validateScene(removalJoined, []).ok, 'joined evidence, metadata and hosts stay valid');
assert(normalizeWallJunctions(withoutDivider(recolored), recolored).walls.length === 2, 'different colors are retained when divider removal cannot safely merge');
const finishConflict = structuredClone(furnishedSplit); finishConflict.project!.finishes = finishConflict.project!.finishes.filter(f => f.entityId === 'long');
assert(normalizeWallJunctions(withoutDivider(finishConflict), finishConflict).walls.length === 2, 'different finish stacks remain separate after divider removal');
const metadataConflict = structuredClone(furnishedSplit); metadataConflict.project!.metadata[second.id]!.structuralRole = 'structural';
assert(normalizeWallJunctions(withoutDivider(metadataConflict), metadataConflict).walls.length === 2, 'incompatible reviewed properties cannot be silently combined');

const reversed = scene([wall('left', [0,0], [3,0]), wall('right', [8,0], [3,0]), wall('divider', [3,0], [3,3])]);
reversed.version = 2; reversed.project = emptyProject();
reversed.walls[1]!.openings = [{ id: 'reverse-door', kind: 'door', offset: 1, width: 1, sill: 0, height: 2 }];
reversed.project.components = [{ id: 'reverse-mount', kind: 'cabinet', name: 'Reverse mount', color: '#eeeeee', phase: 'existing', position: [0,0,0], dimensions: [.5,.5,.2], rotation: .3, host: { wallId: 'right', offset: 3, side: 1, elevation: 1 } }];
const reversePosition = componentPosition(reversed, reversed.project.components[0]!);
const reverseYaw = componentRotation(reversed, reversed.project.components[0]!);
const reverseJoin = normalizeWallJunctions(withoutDivider(reversed), reversed);
assert(reverseJoin.walls.length === 2, 'opposite wall directions with openings stay separate to preserve unresolved opening orientation');
assert(!reverseJoin.project!.metadata['reverse-door'], 'normalization never promotes implicit hinge or swing defaults into recorded properties');
assert(json(componentPosition(reverseJoin, reverseJoin.project!.components[0]!)) === json(reversePosition), 'reversed host keeps physical mounting side and position');
near(Math.cos(componentRotation(reverseJoin, reverseJoin.project!.components[0]!) - reverseYaw), 1, 'reversed host keeps physical rotation');
const reverseWithoutOpening = structuredClone(reversed); reverseWithoutOpening.walls[1]!.openings = [];
const reverseEmptyJoin = normalizeWallJunctions(withoutDivider(reverseWithoutOpening), reverseWithoutOpening);
assert(reverseEmptyJoin.walls.length === 1, 'opposite wall directions without openings still reconnect');
assert(json(componentPosition(reverseEmptyJoin, reverseEmptyJoin.project!.components[0]!)) === json(reversePosition), 'reverse merging without openings preserves mounted world pose');

const tiny = scene([wall('a', [0,0], [4,0]), wall('divider', [.02,0], [.02,2])]);
throws(() => normalizeWallJunctions(tiny), /0\.05|short/i, 'unrepresentable tiny segments reject safely');
const openingConflict = structuredClone(tee); openingConflict.walls[0]!.openings = [{ id: 'conflict', kind: 'window', offset: 2, width: 2, sill: 1, height: 1 }];
throws(() => normalizeWallJunctions(openingConflict), /opening/i, 'junction through an opening rejects without truncating that opening');
const mountedConflict = structuredClone(furnished); mountedConflict.project!.components[0]!.host!.offset = 3;
const mountedBefore = json(mountedConflict);
throws(() => normalizeWallJunctions(mountedConflict), /mount|component/i, 'junction through mounted equipment rejects rather than dropping the host');
assert(json(mountedConflict) === mountedBefore, 'failed normalization leaves caller geometry and dependants untouched');
console.log(`Wall junction checks passed (${assertions} assertions).`);
