"""Plant pieces: one builder per slug plus its manifest metadata. Build with build.py."""
import math

import numpy as np
from mathutils import Matrix, Vector

import parts as P
from parts import Builder, catmull, leaf, mat, pot, tube

COMMON = {"kind": "plant", "source_url": "generated:bpy", "license": "CC0 (generated by varpet)"}
TAU = 2 * math.pi
GOLD = 2.39996323


def interp(xs, ys):
    return lambda s: float(np.interp(s, xs, ys))


def azim(a, elev):
    """Unit vector at azimuth a (radians, 0 = +X) and elevation elev (radians)."""
    return Vector((math.cos(a) * math.cos(elev), math.sin(a) * math.cos(elev), math.sin(elev)))


def bark_mat(name, base, rough=0.85, fissure=0.5, seed=8):
    return mat(name, tex=P.texture_bark(name, base, seed, fissure), rough=rough)


def rad(d):
    return math.radians(d)


# ================================================================ fiddle leaf fig
FIDDLE = interp([0, 0.04, 0.12, 0.25, 0.4, 0.52, 0.62, 0.74, 0.84, 0.92, 0.97, 1.0],
                [0.08, 0.34, 0.5, 0.58, 0.6, 0.62, 0.78, 0.96, 1.0, 0.86, 0.55, 0.05])


def fiddle_leaf_fig():
    rng = P.rng_for("fiddle")
    soil_z, _ = pot("basket", 0.2, 0.34, r_bot=0.16, seed=11)
    col, nrm = P.leaf_texture("fiddle", [dict(base="#22461a", vein="#8ea65c", mid="#b9c67e"),
                                         dict(base="#386621", vein="#9cb866", mid="#c6d28a")],
                              n_veins=9, vein_k=0.22, vein_p=1.2, vein_w=0.06, vein_amt=0.4, mid_amt=0.7,
                              mid_w=0.02, seed=2)
    L, W = Builder(), Builder()
    trunk = catmull([(0, 0, soil_z - 0.02), (0.01, 0.0, 0.5), (-0.015, 0.01, 0.9), (0.0, -0.01, 1.2), (0.01, 0.0, 1.42)], 6)
    tube(W, trunk, lambda t: 0.022 - 0.014 * t, sides=10)
    stems = [(trunk, 0.36, 1.0, 26, 0.0)]
    for ang, z0, ln in ((0.6, 0.78, 0.36), (3.5, 0.95, 0.3)):
        p0, _ = P.point_on(trunk, (z0 - soil_z) / (1.42 - soil_z))
        br = catmull([p0, p0 + azim(ang, 0.7) * ln * 0.5, p0 + azim(ang, 1.0) * ln], 5)
        tube(W, br, lambda t: 0.011 - 0.006 * t, sides=8)
        stems.append((br, 0.25, 1.0, 9, ang))
    k = 0
    for pts, t0, t1, n, a0 in stems:
        for i in range(n):
            t = t0 + (t1 - t0) * i / (n - 1)
            p, tan = P.point_on(pts, min(t, 0.999))
            top = i / (n - 1)
            a = a0 + k * GOLD + rng.uniform(-0.3, 0.3)
            k += 1
            elev = rad(-5 + 55 * top ** 1.5 + rng.uniform(-10, 10))
            ln = (0.25 + 0.12 * math.sin(math.pi * min(1, 0.3 + top))) * rng.uniform(0.9, 1.1)
            if top > 0.9:
                ln *= 0.7
            pet = p + azim(a, elev + 0.4) * 0.035
            tube(W, [p, pet], 0.004, sides=5, cap_end=False)
            leaf(L, pet, azim(a, elev), ln, ln * 0.62, FIDDLE, nu=14, nv=7, bend=0.35 + 0.3 * (1 - top),
                 cup=0.14, fold=0.1, wave=0.07, wave_n=7, roll=rng.uniform(-0.25, 0.25),
                 variant=1 if top > 0.85 else 0, nvar=2, side_bend=rng.uniform(-0.2, 0.2))
    W.obj("wood", bark_mat("fig-bark", "#6f6556", 0.8, 0.25))
    L.obj("leaves", mat("fiddle-leaf", tex=col, normal=nrm, nstrength=0.6, rough=0.32))


# ================================================================ olive tree
def olive_tree():
    rng = P.rng_for("olive")
    soil_z, _ = pot("terracotta", 0.19, 0.3, r_bot=0.14, seed=21)
    col, nrm = P.leaf_texture("olive", [dict(base="#4a5a34", vein="#5d6b45", mid="#8a9570"),
                                        dict(base="#7d8a6c", vein="#909c80", mid="#a8b196")],
                              W=256, TH=64, n_veins=1, vein_amt=0.0, mid_w=0.06, mid_amt=0.5, mottle=0.08, seed=3)
    L, W = Builder(), Builder()
    stats = {"leaves": 0}

    def branch(p0, d, length, r0, depth):
        n = 4
        ctrl = [p0]
        dd = d.normalized()
        for i in range(n):
            dd = (dd + Vector((rng.uniform(-0.35, 0.35), rng.uniform(-0.35, 0.35), rng.uniform(-0.1, 0.25)))).normalized()
            ctrl.append(ctrl[-1] + dd * length / n)
        pts = catmull(ctrl, 3 if depth else 2)
        tube(W, pts, lambda t: r0 * (1 - 0.6 * t), sides=7 if depth >= 3 else (5 if depth == 2 else 3), jitter=0.25 if depth >= 2 else 0, rng=rng)
        if depth == 0:
            m = 8
            for i in range(m):
                t = 0.2 + 0.8 * i / m
                p, tan = P.point_on(pts, t)
                side = tan.cross(Vector((0, 0, 1)))
                if side.length < 1e-3:
                    side = Vector((1, 0, 0))
                side.normalize()
                rot = Matrix.Rotation(i * 1.4, 3, tan)
                for sgn in (1, -1):
                    dirv = (tan * 0.75 + (rot @ side) * sgn * 0.65 + Vector((0, 0, -0.1))).normalized()
                    ln = rng.uniform(0.05, 0.07)
                    P.strip_leaf(L, p, dirv, ln, ln * 0.18, nu=4, bend=rng.uniform(0.1, 0.5), fold=0.3,
                                 variant=1 if rng.random() < 0.3 else 0, nvar=2, twist=rng.uniform(-0.8, 0.8))
                    stats["leaves"] += 1
            P.strip_leaf(L, pts[-1], tan, 0.055, 0.01, nu=4, bend=0.2, variant=0, nvar=2)
            return
        kids = {3: 3, 2: 3, 1: 3}[depth]
        for c in range(kids):
            t = 0.45 + 0.55 * (c + 1) / kids
            p, tan = P.point_on(pts, min(t, 0.98))
            a = math.atan2(tan.y, tan.x) + rng.uniform(-1.3, 1.3) + (c % 2 - 0.5) * 1.2
            elev = rng.uniform(0.3, 0.95)
            branch(p, azim(a, elev), length * rng.uniform(0.5, 0.7), r0 * 0.6, depth - 1)

    # two leaning intertwined trunks, then a loose crown
    t1 = catmull([(0, 0, soil_z - 0.03), (0.03, 0.01, 0.45), (-0.02, 0.03, 0.62), (0.02, 0.0, 0.76)], 5)
    t2 = catmull([(0.02, -0.02, soil_z - 0.03), (-0.03, -0.02, 0.46), (0.01, -0.03, 0.6), (-0.03, -0.01, 0.7)], 5)
    tube(W, t1, lambda t: 0.028 - 0.01 * t, sides=10, jitter=0.35, rng=rng)
    tube(W, t2, lambda t: 0.022 - 0.008 * t, sides=10, jitter=0.35, rng=rng)
    for i, (tp, a) in enumerate(((t1, 0.3), (t1, 2.4), (t2, 4.2), (t2, 5.5), (t1, 1.3))):
        p = tp[-1] if i < 4 else P.point_on(tp, 0.8)[0]
        branch(p, azim(a, rng.uniform(0.55, 0.9)), rng.uniform(0.3, 0.38), 0.014, 3)
    W.obj("wood", bark_mat("olive-bark", "#8a8578", 0.9, 0.55))
    L.obj("leaves", mat("olive-leaf", tex=col, normal=nrm, nstrength=0.3, rough=0.55))


# ================================================================ monstera
MONSTERA = interp([0, 0.06, 0.15, 0.35, 0.55, 0.72, 0.85, 0.94, 1.0],
                  [0.62, 0.86, 0.97, 1.0, 0.94, 0.78, 0.55, 0.3, 0.03])


def _monstera_alpha(S, T, k):
    at = np.abs(T) * 2
    a = np.ones_like(S)
    a[(S < 0.13) & (at < 0.3 * (1 - S / 0.13))] = 0  # cordate notch
    n = 8 if k == 0 else 6
    phase = (S - 0.2 * at ** 1.1) * n + 0.5
    d = np.abs(phase - np.round(phase))
    inner = 0.3 if k == 0 else 0.55
    wedge = 0.03 + 0.06 * np.clip((at - inner) / (1 - inner), 0, 1)
    band = (S > 0.14) & (S < 0.9)
    a[(d < wedge) & (at > inner) & band] = 0
    if k == 0:
        hole = ((at - 0.17) / 0.055) ** 2 + (d / 0.07) ** 2 < 1
        a[hole & band & (S < 0.8)] = 0
    return a


def monstera():
    rng = P.rng_for("monstera")
    soil_z, _ = pot("ceramic", 0.19, 0.3, r_bot=0.15, seed=31)
    col, nrm = P.leaf_texture("monstera", [dict(base="#1c4318", vein="#3f6b2a", mid="#5f8a3c"),
                                           dict(base="#2e5d1f", vein="#4f7c34", mid="#6f9848")],
                              n_veins=8, vein_k=0.2, vein_p=1.1, vein_w=0.08, vein_amt=0.4, mid_w=0.02,
                              mid_amt=0.8, alpha_fn=_monstera_alpha, seed=4, nstrength=2.0)
    L, S = Builder(), Builder()
    n = 9
    for i in range(n):
        a = i * GOLD + rng.uniform(-0.2, 0.2)
        young = i >= n - 2
        h = rng.uniform(0.42, 0.78) if not young else rng.uniform(0.75, 0.9)
        reach = rng.uniform(0.18, 0.38) if not young else 0.08
        base = Vector((0.03 * math.cos(a), 0.03 * math.sin(a), soil_z - 0.02))
        top = Vector((reach * math.cos(a), reach * math.sin(a), h))
        mid = base.lerp(top, 0.5) + Vector((0, 0, 0.12)) - Vector((math.cos(a), math.sin(a), 0)) * reach * 0.25
        pts = catmull([base, mid, top], 8)
        tube(S, pts, lambda t: 0.009 - 0.004 * t, sides=7)
        ln = rng.uniform(0.36, 0.46) if not young else 0.26
        elev = rad(rng.uniform(-15, 15)) if not young else rad(40)
        d = azim(a + rng.uniform(-0.2, 0.2), elev)
        lb = top - d * ln * 0.12
        leaf(L, lb, d, ln, ln * 0.92, MONSTERA, nu=14, nv=9, bend=rng.uniform(0.4, 0.8), cup=0.06, fold=0.05,
             wave=0.03, roll=rng.uniform(-0.3, 0.3), variant=1 if young else 0, nvar=2)
    # two aerial roots
    for a in (1.0, 3.9):
        r0 = Vector((0.05 * math.cos(a), 0.05 * math.sin(a), soil_z + 0.1))
        tube(S, catmull([r0, r0 + Vector((0.04 * math.cos(a), 0.04 * math.sin(a), 0.05)),
                         Vector((0.14 * math.cos(a), 0.14 * math.sin(a), soil_z + 0.02))], 5), 0.004, sides=5)
    S.obj("stems", mat("monstera-stem", "#4d6b2e", rough=0.5))
    L.obj("leaves", mat("monstera-leaf", tex=col, normal=nrm, nstrength=0.5, rough=0.3, alpha=True))


# ================================================================ snake plant
SWORD = interp([0, 0.08, 0.35, 0.65, 0.85, 0.95, 1.0], [0.5, 0.8, 1.0, 0.9, 0.55, 0.22, 0.0])


def _snake_paint(S, T, col, rng, k):
    n = P.fbm(S.shape[0], S.shape[1], 3, 24, rng, 3)
    phase = S * 34 + 0.35 * np.abs(np.sin(T * 30)) + 1.6 * n
    band = np.clip((np.sin(phase * TAU) - 0.25) / 0.5, 0, 1) * (0.55 + 0.45 * n)
    light = P.rgb("#8fa98a")
    at = np.abs(T) * 2
    band *= (at < 0.8)
    out = col * (1 - 0.65 * band[..., None]) + light * 0.65 * band[..., None]
    return out


def snake_plant():
    rng = P.rng_for("snake")
    soil_z, _ = pot("concrete", 0.15, 0.27, r_bot=0.13, seed=41)
    col, nrm = P.leaf_texture("snake", [dict(base="#1c3620", vein="#1c3620", mid="#23402a")] * 2,
                              W=1024, TH=256, n_veins=1, vein_amt=0.0, mid_amt=0.2, mid_w=0.1,
                              margin_col="#d6c65a", margin_w=0.12, paint=_snake_paint, seed=5, nstrength=0.5)
    L = Builder()
    n = 12
    for i in range(n):
        a = i * GOLD
        rr = 0.02 + 0.07 * math.sqrt(i / n)
        base = Vector((rr * math.cos(a), rr * math.sin(a), soil_z - 0.01))
        centre = 1 - i / n
        ln = rng.uniform(0.3, 0.42) + 0.16 * centre
        lean = rad(4 + 16 * (1 - centre) + rng.uniform(-3, 3))
        d = azim(a + rng.uniform(-0.3, 0.3), math.pi / 2 - lean)
        leaf(L, base, d, ln, rng.uniform(0.055, 0.075), SWORD, nu=12, nv=7, bend=rng.uniform(-0.05, 0.15),
             cup=0.25, fold=0.2, twist=rng.uniform(-0.6, 0.6), roll=rng.uniform(0, TAU), wave=0.03, wave_n=3,
             variant=i % 2, nvar=2, up=azim(a + math.pi / 2, 0))
    L.obj("leaves", mat("snake-leaf", tex=col, normal=nrm, nstrength=0.4, rough=0.4))


# ================================================================ bird of paradise
PARADISE = interp([0, 0.04, 0.15, 0.4, 0.7, 0.86, 0.95, 1.0], [0.15, 0.55, 0.88, 1.0, 0.95, 0.72, 0.4, 0.04])


def _paradise_alpha(S, T, k):
    import random
    r = random.Random(50 + k)
    at = np.abs(T) * 2
    a = np.ones_like(S)
    for _ in range(r.randint(3, 6)):
        s0 = r.uniform(0.15, 0.9)
        sgn = r.choice((1, -1))
        depth = r.uniform(0.25, 0.8)
        w = r.uniform(0.002, 0.006)
        a[(np.abs(S - s0 - 0.04 * at) < w * (0.4 + at)) & (np.sign(T) == sgn) & (at > 1 - depth)] = 0
    return a


def bird_of_paradise():
    rng = P.rng_for("paradise")
    soil_z, _ = pot("black", 0.21, 0.36, r_bot=0.17, seed=51)
    col, nrm = P.leaf_texture("paradise", [dict(base="#2f5a24", vein="#4c7a37", mid="#c9d38f"),
                                           dict(base="#35652a", vein="#57873f", mid="#cfd99a"),
                                           dict(base="#3d6f2c", vein="#5f9045", mid="#d6dfa3")],
                              TH=320, n_veins=46, vein_k=0.06, vein_w=0.12, vein_amt=0.22, mid_w=0.028, mid_amt=0.9,
                              alpha_fn=_paradise_alpha, seed=6, nstrength=1.5)
    L, S = Builder(), Builder()
    clumps = [(0.0, 0.0, 0.3), (0.06, 0.04, 1.9), (-0.05, 0.05, 3.2)]
    k = 0
    for cx, cy, fan in clumps:
        nrmv = azim(fan, 0)
        inplane = azim(fan + math.pi / 2, 0)
        nleaf = 4
        for j in range(nleaf):
            ang = rad(-38 + 76 * j / (nleaf - 1) + rng.uniform(-6, 6))
            d = (Vector((0, 0, 1)) * math.cos(ang) + inplane * math.sin(ang)).normalized()
            d = (d + nrmv * rng.uniform(-0.12, 0.12)).normalized()
            plen = rng.uniform(0.55, 0.8) * (0.8 if abs(ang) > rad(30) else 1.0)
            base = Vector((cx, cy, soil_z - 0.02))
            top = base + d * plen
            pts = catmull([base, base + d * plen * 0.5 + nrmv * 0.01, top], 6)
            tube(S, pts, lambda t: 0.013 - 0.006 * t, sides=7)
            ln = rng.uniform(0.5, 0.62)
            leaf(L, top, (d + Vector((0, 0, 0.3))).normalized(), ln, ln * rng.uniform(0.36, 0.42), PARADISE,
                 nu=16, nv=7, bend=rng.uniform(0.5, 1.0) * (1 if k % 2 else -1), cup=0.12, fold=0.06, wave=0.05,
                 wave_n=5, twist=rng.uniform(-0.3, 0.3), variant=k % 3, nvar=3, up=nrmv, side_bend=rng.uniform(-0.3, 0.3))
            k += 1
        # sheath at the clump base
        tube(S, [Vector((cx, cy, soil_z - 0.02)), Vector((cx, cy, soil_z + 0.1))], lambda t: 0.03 - 0.012 * t, sides=9)
    S.obj("stems", mat("paradise-stem", "#5b7440", rough=0.55))
    L.obj("leaves", mat("paradise-leaf", tex=col, normal=nrm, nstrength=0.4, rough=0.45, alpha=True))


# ================================================================ rubber plant
RUBBER = interp([0, 0.05, 0.2, 0.45, 0.7, 0.86, 0.96, 1.0], [0.12, 0.5, 0.85, 1.0, 0.88, 0.55, 0.18, 0.0])


def rubber_plant():
    rng = P.rng_for("rubber")
    soil_z, _ = pot("ceramic", 0.16, 0.28, r_bot=0.13, seed=61)
    col, nrm = P.leaf_texture("rubber", [dict(base="#1b3317", vein="#2d4a24", mid="#d9cfa2"),
                                         dict(base="#3a2a1d", vein="#4b3526", mid="#b56a4c")],
                              n_veins=26, vein_k=0.06, vein_w=0.1, vein_amt=0.12, mid_w=0.016, mid_amt=0.85,
                              seed=7, nstrength=0.8)
    L, S = Builder(), Builder()
    for sx, sy, top_z, nl, lean in ((0.0, 0.0, 1.08, 15, 0.0), (0.05, -0.03, 0.82, 11, 0.25)):
        pts = catmull([(sx, sy, soil_z - 0.02), (sx + lean * 0.1, sy - lean * 0.05, (soil_z + top_z) / 2),
                       (sx + lean * 0.25, sy - lean * 0.12, top_z)], 8)
        tube(S, pts, lambda t: 0.013 - 0.006 * t, sides=8)
        for i in range(nl):
            t = 0.28 + 0.7 * i / (nl - 1)
            p, tan = P.point_on(pts, min(t, 0.995))
            top = i / (nl - 1)
            a = i * GOLD + sx * 20
            elev = rad(5 + 40 * top + rng.uniform(-8, 8))
            ln = rng.uniform(0.22, 0.29) * (0.65 if top > 0.92 else 1)
            pet = p + azim(a, elev + 0.5) * 0.045
            tube(S, [p, pet], 0.0035, sides=5, cap_end=False)
            leaf(L, pet, azim(a, elev), ln, ln * 0.48, RUBBER, nu=12, nv=7, bend=0.3 + 0.2 * (1 - top), cup=0.04,
                 fold=0.1, roll=rng.uniform(-0.2, 0.2), variant=1 if top > 0.9 else 0, nvar=2)
        # rosy sheath wrapping the new leaf at the tip
        tip = pts[-1]
        tube(S, [tip, tip + tan * 0.07], lambda t: 0.009 * (1 - t) + 0.001, sides=8)
    S.obj("stems", mat("rubber-stem", "#5a5a36", rough=0.5))
    L.obj("leaves", mat("rubber-leaf", tex=col, normal=nrm, nstrength=0.4, rough=0.16))


# ================================================================ kentia palm
def kentia_palm():
    rng = P.rng_for("kentia")
    soil_z, _ = pot("terracotta", 0.23, 0.38, r_bot=0.18, seed=71, tint="#a95d3c")
    col, nrm = P.leaf_texture("kentia", [dict(base="#2b5222", vein="#355e2a", mid="#6e8f45"),
                                         dict(base="#3a6a2a", vein="#467634", mid="#7f9f52")],
                              W=512, TH=64, n_veins=1, vein_amt=0.0, mid_w=0.05, mid_amt=0.6, seed=8, nstrength=0.4)
    L, S = Builder(), Builder()
    nf = 8
    for f in range(nf):
        a = f * GOLD + rng.uniform(-0.15, 0.15)
        young = f == nf - 1
        out = azim(a, 0)
        h = rng.uniform(0.75, 1.05) if not young else rng.uniform(1.15, 1.3)
        reach = rng.uniform(0.35, 0.6) if not young else 0.2
        base = Vector((0.02 * math.cos(a), 0.02 * math.sin(a), soil_z - 0.02))
        ctrl = [base, base + Vector((0, 0, h * 0.45)) + out * reach * 0.1, base + Vector((0, 0, h)) + out * reach * 0.55,
                base + Vector((0, 0, h - (0.25 if not young else 0.05))) + out * reach]
        pts = P.resample(catmull(ctrl, 10), 0.02)
        tube(S, pts, lambda t: 0.009 - 0.007 * t, sides=6)
        nl = 26
        for i in range(nl):
            t = 0.42 + 0.56 * i / nl
            p, tan = P.point_on(pts, t)
            side = tan.cross(Vector((0, 0, 1)))
            side = side.normalized() if side.length > 1e-3 else out.cross(Vector((0, 0, 1))).normalized()
            u = (i + 0.5) / nl
            ln = (0.14 + 0.28 * math.sin(math.pi * min(1, u * 1.15)) ** 0.8) * (0.7 if young else 1)
            for sgn in (1, -1):
                dirv = (tan * 0.75 + side * sgn * 0.65 + Vector((0, 0, 0.1 if young else -0.1))).normalized()
                P.strip_leaf(L, p, dirv, ln, 0.026, nu=6, bend=(1.2 if young else rng.uniform(1.4, 2.0)), fold=0.45,
                             variant=1 if young else 0, nvar=2, twist=sgn * rng.uniform(0.0, 0.5),
                             outline=lambda s: min(1.0, s * 8) * (1 - s) ** 0.3 + 0.05)
    S.obj("stems", mat("kentia-stem", "#56703a", rough=0.5))
    L.obj("leaves", mat("kentia-leaf", tex=col, normal=nrm, nstrength=0.3, rough=0.42))


# ================================================================ ZZ plant
ZZ = interp([0, 0.08, 0.3, 0.55, 0.8, 0.93, 1.0], [0.2, 0.6, 0.95, 1.0, 0.75, 0.4, 0.0])


def zz_plant():
    rng = P.rng_for("zz")
    soil_z, _ = pot("ceramic", 0.13, 0.22, r_bot=0.11, seed=81, tint="#e4ddd0")
    col, nrm = P.leaf_texture("zz", [dict(base="#173513", vein="#1f4119", mid="#2c5222"),
                                     dict(base="#2e5a1c", vein="#386826", mid="#46762e")],
                              W=256, TH=128, n_veins=5, vein_k=0.2, vein_amt=0.12, mid_w=0.03, mid_amt=0.4, seed=9,
                              nstrength=0.5)
    L, S = Builder(), Builder()
    n = 9
    for i in range(n):
        a = i * GOLD
        rr = 0.015 + 0.05 * math.sqrt(i / n)
        base = Vector((rr * math.cos(a), rr * math.sin(a), soil_z - 0.01))
        young = i >= n - 2
        ln = rng.uniform(0.26, 0.38) if not young else 0.3
        lean = rad(rng.uniform(14, 36) if not young else 5)
        d0 = azim(a, math.pi / 2 - lean)
        pts = catmull([base, base + d0 * ln * 0.5, base + azim(a, math.pi / 2 - lean * 1.8) * ln], 8)
        tube(S, pts, lambda t: 0.007 * (1 - t) ** 2 + 0.0025, sides=7)
        pairs = 7
        for j in range(pairs):
            t = 0.35 + 0.6 * j / pairs
            p, tan = P.point_on(pts, t)
            side = tan.cross(azim(a + math.pi / 2, 0)).normalized()
            side = azim(a + math.pi / 2, 0)
            ll = rng.uniform(0.06, 0.075) * (0.7 if young else 1) * (0.85 if j == pairs - 1 else 1)
            for sgn in (1, -1):
                dv = (tan * 0.55 + side * sgn * 0.8).normalized()
                leaf(L, p, dv, ll, ll * 0.5, ZZ, nu=7, nv=5, bend=0.25, cup=0.1, fold=0.08,
                     variant=1 if young else 0, nvar=2, up=azim(a, 0.6))
        p, tan = pts[-1], (pts[-1] - pts[-2]).normalized()
        leaf(L, p, tan, 0.06, 0.03, ZZ, nu=7, nv=5, bend=0.2, cup=0.1, variant=1 if young else 0, nvar=2)
    S.obj("stems", mat("zz-stem", "#3d5a26", rough=0.35))
    L.obj("leaves", mat("zz-leaf", tex=col, normal=nrm, nstrength=0.3, rough=0.14))


# ================================================================ pothos
HEART = interp([0, 0.06, 0.18, 0.4, 0.65, 0.85, 0.95, 1.0], [0.55, 0.85, 1.0, 0.92, 0.62, 0.3, 0.12, 0.0])


def _pothos_paint(S, T, col, rng, k):
    streak = P.fbm(S.shape[0], S.shape[1], 18, 4, rng, 3)
    at = np.abs(T) * 2
    y = np.clip((streak - (0.58 if k == 0 else 0.5)) / 0.08, 0, 1) * (0.4 + 0.6 * at)
    return col * (1 - 0.85 * y[..., None]) + P.rgb("#e2dc8a") * 0.85 * y[..., None]


def pothos_trailing():
    rng = P.rng_for("pothos")
    soil_z, r_in = pot("terracotta", 0.085, 0.13, r_bot=0.065, seed=91)
    col, nrm = P.leaf_texture("pothos", [dict(base="#2f5e1a", vein="#4d7c2e", mid="#7aa04c"),
                                         dict(base="#3d6f22", vein="#5b8a38", mid="#8db45c")],
                              W=512, TH=256, n_veins=6, vein_k=0.3, vein_w=0.06, vein_amt=0.25, mid_w=0.025,
                              mid_amt=0.6, paint=_pothos_paint, seed=10, nstrength=0.6)
    L, S = Builder(), Builder()

    def heart(p, d, ln, var, up=None, bend=0.35):
        lb = p - d * ln * 0.12
        leaf(L, lb, d, ln, ln * 0.78, HEART, nu=9, nv=7, bend=bend, cup=0.12, fold=0.12, variant=var, nvar=2,
             roll=rng.uniform(-0.3, 0.3), up=up)

    # crown mound
    for i in range(22):
        a = i * GOLD
        rr = r_in * 0.6 * math.sqrt((i + 1) / 22)
        p0 = Vector((rr * math.cos(a), rr * math.sin(a), soil_z))
        elev = rad(rng.uniform(15, 55))
        top = p0 + azim(a, rad(60)) * rng.uniform(0.04, 0.09)
        tube(S, [p0, top], 0.002, sides=4, cap_end=False)
        heart(top, azim(a + rng.uniform(-0.4, 0.4), elev), rng.uniform(0.06, 0.085), i % 2)
    # vines over the rim, down the pot and along the shelf
    for v in range(7):
        a = rad(-90 + (v - 3) * 42 + rng.uniform(-10, 10))
        o = azim(a, 0)
        sd = azim(a + math.pi / 2, 0)
        run = rng.uniform(0.12, 0.3)
        wig = rng.uniform(-0.06, 0.06)
        ctrl = [o * r_in * 0.4 + Vector((0, 0, soil_z + 0.01)), o * (0.09) + Vector((0, 0, 0.145)),
                o * 0.1 + Vector((0, 0, 0.08)), o * 0.115 + sd * wig * 0.3 + Vector((0, 0, 0.012)),
                o * (0.115 + run * 0.5) + sd * wig + Vector((0, 0, 0.006)), o * (0.115 + run) + sd * wig * 0.5 + Vector((0, 0, 0.006))]
        pts = P.resample(catmull(ctrl, 8), 0.01)
        tube(S, pts, 0.0022, sides=4)
        nl = int(len(pts) / 5)
        for j in range(1, nl):
            t = j / nl
            p, tan = P.point_on(pts, t)
            hang = p.z > 0.02 and p.z < 0.13
            sgn = 1 if j % 2 else -1
            if hang:
                d = (o * 0.9 + sd * sgn * 0.5 + Vector((0, 0, -0.4))).normalized()
                heart(p + o * 0.01, d, rng.uniform(0.045, 0.06), (j + v) % 2, bend=0.2)
            else:
                d = (tan * 0.6 + sd * sgn * 0.7 + Vector((0, 0, 0.35))).normalized()
                heart(p, d, rng.uniform(0.045, 0.065) * (0.7 if t > 0.9 else 1), (j + v) % 2, bend=0.45)
    S.obj("vines", mat("pothos-vine", "#6c8a3c", rough=0.5))
    L.obj("leaves", mat("pothos-leaf", tex=col, normal=nrm, nstrength=0.4, rough=0.3))


# ================================================================ succulents trio
SPOON = interp([0, 0.2, 0.5, 0.75, 0.9, 1.0], [0.35, 0.6, 0.9, 1.0, 0.8, 0.0])
SPIKE = interp([0, 0.2, 0.5, 0.8, 1.0], [0.8, 1.0, 0.75, 0.35, 0.0])


def _echeveria_paint(S, T, col, rng, k):
    tip = np.clip((S - 0.75) / 0.25, 0, 1) ** 1.5
    edge = np.clip((np.abs(T) * 2 - 0.8) / 0.2, 0, 1) * (S > 0.4)
    m = np.maximum(tip, edge * 0.6)[..., None]
    return col * (1 - m) + P.rgb("#c47f86") * m


def _haworthia_paint(S, T, col, rng, k):
    n = P.fbm(S.shape[0], S.shape[1], 4, 20, rng, 2)
    ph = S * 16 + 0.4 * n
    band = np.clip((np.sin(ph * TAU) - 0.55) / 0.3, 0, 1)
    dots = (rng.random(S.shape) > 0.97) * 0.8
    m = np.clip(band + dots, 0, 1)[..., None]
    return col * (1 - 0.8 * m) + P.rgb("#e8eadf") * 0.8 * m


def _rosette(L, cx, cz, n, ln0, ln1, e0, e1, width, outline, variant, rng, thick=0.35, cup=0.3, bend=-0.3, spread=0.004):
    for i in range(n):
        f = i / (n - 1)
        a = i * GOLD
        ln = ln0 + (ln1 - ln0) * f
        elev = rad(e0 + (e1 - e0) * f)
        p = Vector((cx, 0, cz)) + azim(a, 0) * spread * (1 - f)
        leaf(L, p, azim(a, elev), ln, ln * width, outline, nu=6, nv=5, bend=bend, cup=cup, thick=thick,
             variant=variant, nvar=3)


def succulent_trio():
    rng = P.rng_for("succulents")
    col, nrm = P.leaf_texture("succulent", [dict(base="#8fb0a4", vein="#8fb0a4", mid="#9dbab0"),
                                            dict(base="#2d4a2c", vein="#2d4a2c", mid="#35533a"),
                                            dict(base="#6f9a55", vein="#6f9a55", mid="#7fa862")],
                              W=256, TH=128, n_veins=1, vein_amt=0.0, mid_amt=0.1, mottle=0.06, seed=11, nstrength=0.3,
                              paint=lambda S, T, c, r, k: _echeveria_paint(S, T, c, r, k) if k == 0 else
                              (_haworthia_paint(S, T, c, r, k) if k == 1 else c))
    L = Builder()
    xs = (-0.14, 0.0, 0.14)
    specs = (("concrete", 0.055, 0.075, "#a8a6a0"), ("ceramic", 0.05, 0.08, "#ece8e0"), ("terracotta", 0.055, 0.07, None))
    objs = []
    for x, (style, r, h, tint) in zip(xs, specs):
        before = set(P.kit.meshes())
        soil_z, _ = pot(style, r, h, r_bot=r * 0.82, wall=0.007, soil_drop=0.012, steps=40, seed=100 + int(x * 100),
                        tint=tint, cover="gravel")
        for o in set(P.kit.meshes()) - before:
            o.location.x += x
    # echeveria (blue-grey, pink tips)
    _rosette(L, xs[0], 0.078, 34, 0.056, 0.012, 22, 80, 0.6, SPOON, 0, rng, thick=0.3, cup=0.35, bend=-0.4)
    # zebra haworthia (dark, white bands, upright spikes)
    _rosette(L, xs[1], 0.076, 22, 0.07, 0.03, 38, 82, 0.3, SPIKE, 1, rng, thick=0.45, cup=0.35, bend=-0.1)
    # small jade-like crassula cluster
    for c in range(5):
        a = c * GOLD
        base = Vector((xs[2] + 0.015 * math.cos(a), 0.015 * math.sin(a), 0.058))
        stem_top = base + azim(a, rad(65)) * 0.05
        for j in range(3):
            p = base.lerp(stem_top, (j + 1) / 3)
            for sgn in (1, -1):
                d = azim(a + sgn * 1.5 + j * 0.8, rad(35))
                leaf(L, p, d, 0.022, 0.014, SPOON, nu=5, nv=5, bend=-0.2, cup=0.2, thick=0.5, variant=2, nvar=3)
    L.obj("leaves", mat("succulent-leaf", tex=col, normal=nrm, nstrength=0.3, rough=0.5))


# ================================================================ pampas in floor vase
def _feather_alpha(S, T, k):
    """Fine diverging fibres from the card base (u) spreading across (v): reads as fluff, not a feather."""
    rng = np.random.default_rng(90 + k)
    H, W = S.shape
    a = np.zeros((H, W))
    cols = np.arange(W)
    for _ in range(50):
        v0 = rng.uniform(0.4, 0.6)
        v1 = np.clip(v0 + (v0 - 0.5) * rng.uniform(1.0, 2.6) + rng.normal(0, 0.12), 0.02, 0.98)
        end = rng.uniform(0.55, 1.0)
        s = cols / (W - 1)
        m = s <= end
        curve = v0 + (v1 - v0) * (s ** 0.7) + 0.02 * np.sin(s * rng.uniform(4, 9) + rng.uniform(0, 6))
        rows = np.clip((curve * (H - 1)).astype(int), 0, H - 1)
        a[rows[m], cols[m]] = 1
    return a


def pampas_vase():
    rng = P.rng_for("pampas")
    B = Builder()
    vz = [0.012, 0.06, 0.12, 0.2, 0.27, 0.34, 0.4, 0.44, 0.47, 0.49]
    vr = [0.1, 0.135, 0.162, 0.175, 0.165, 0.13, 0.085, 0.064, 0.06, 0.066]
    prof = [(0, 0.004), (0.09, 0)] + [(float(np.interp(z, vz, vr)), z) for z in np.linspace(0.012, 0.49, 20)]
    prof += [(0.076, 0.505), (0.07, 0.508), (0.064, 0.49), (0.05, 0.42), (0, 0.42)]
    P.lathe(B, prof, steps=56, v_scale=1.0)
    B.obj("vase", mat("vase", tex=P.texture_speckle("vase-stone", "#d8cfc0", 94, 0.07, 0.006), rough=0.75))
    col = P.image("pampas", np.dstack((P.rgb("#dbc49c") * (0.8 + 0.3 * P.fbm(256, 512, 6, 3, np.random.default_rng(3), 3)[..., None])
                                       * np.ones((256, 512, 3)), np.vstack([_feather_alpha(*np.meshgrid(np.linspace(0, 1, 512), np.linspace(-0.5, 0.5, 128)), k) for k in range(2)]))))
    F, S, C = Builder(), Builder(), Builder()
    n = 10
    for i in range(n):
        a = i * GOLD
        lean = rad(6 + 22 * math.sqrt(i / n) + rng.uniform(-4, 4))
        ln = rng.uniform(1.0, 1.25) - 0.1 * i / n
        base = Vector((0.02 * math.cos(a), 0.02 * math.sin(a), 0.3))
        d = azim(a, math.pi / 2 - lean)
        tip = base + d * ln + Vector((math.cos(a), math.sin(a), 0)) * 0.05 * (i / n)
        pts = P.resample(catmull([base, base.lerp(tip, 0.5) + azim(a, 0) * 0.02, base.lerp(tip, 0.85), tip + azim(a, -0.3) * 0.06], 8), 0.03)
        tube(S, pts, 0.0028, sides=5)
        plume = rng.uniform(0.32, 0.42)
        t0 = 1 - plume / ln
        core = [pp for pp in pts[int(t0 * (len(pts) - 1)):]]
        if len(core) >= 2:
            core = P.resample(catmull(core, 4), 0.015)
            tube(C, core, lambda t: 0.028 * math.sin(math.pi * min(1.0, 0.08 + t)) ** 0.8 + 0.003, sides=8, v_scale=3.0)
        nc = 150
        for c in range(nc):
            t = t0 + (1 - t0) * c / nc
            p, tan = P.point_on(pts, min(t, 0.999))
            u = c / nc
            cl = (0.05 + 0.07 * math.sin(math.pi * min(1, 0.1 + u * 0.95))) * rng.uniform(0.8, 1.2)
            az = c * GOLD
            side = tan.cross(Vector((0, 0, 1)))
            side = side.normalized() if side.length > 1e-3 else Vector((1, 0, 0))
            spin = Matrix.Rotation(az, 3, tan) @ side
            dv = (tan * 0.75 + spin * 0.65).normalized()
            leaf(F, p, dv, cl, cl * 0.8, lambda s: 1.0, nu=4, nv=3, bend=rng.uniform(0.2, 0.9), cup=0.0,
                 twist=rng.uniform(-0.6, 0.6), roll=az, variant=c % 2, nvar=2)
    S.obj("stems", mat("pampas-stem", "#cdb88f", rough=0.8))
    F.obj("plumes", mat("pampas-plume", tex=col, rough=0.95, alpha=True))
    C.obj("plume-core", mat("pampas-core", tex=col, rough=0.95))


# ================================================================ ficus bonsai
BONSAI = interp([0, 0.1, 0.35, 0.65, 0.88, 1.0], [0.3, 0.7, 1.0, 0.9, 0.5, 0.0])


def ficus_bonsai():
    rng = P.rng_for("bonsai")
    before = set(P.kit.meshes())
    soil_z, r_in = pot("bowl", 0.16, 0.055, r_bot=0.12, wall=0.008, soil_drop=0.012, steps=64, seed=111, cover="moss",
                       tint="#35505e")
    for o in set(P.kit.meshes()) - before:
        o.scale.x = 1.35
    col, nrm = P.leaf_texture("bonsai", [dict(base="#1f4516", vein="#2c5520", mid="#58803a"),
                                         dict(base="#3a6d22", vein="#467a2c", mid="#6a9446")],
                              W=256, TH=128, n_veins=5, vein_k=0.2, vein_amt=0.15, mid_w=0.03, mid_amt=0.5, seed=12)
    L, W = Builder(), Builder()
    trunk = catmull([(0.0, 0, soil_z - 0.01), (0.03, 0.0, 0.1), (-0.025, 0.01, 0.17), (0.01, 0.0, 0.24), (0.0, 0.0, 0.28)], 7)
    tube(W, trunk, lambda t: 0.034 * (1 - t) ** 1.2 + 0.008, sides=12, jitter=0.2, rng=rng)
    # nebari: surface roots
    for r in range(6):
        a = r * TAU / 6 + rng.uniform(-0.3, 0.3)
        tube(W, catmull([(0, 0, soil_z + 0.012), azim(a, -0.3) * 0.05 + Vector((0, 0, soil_z + 0.006)),
                         azim(a, 0) * 0.1 + Vector((0, 0, soil_z - 0.002))], 4), lambda t: 0.012 * (1 - t) + 0.002, sides=6)
    pads = [(0.3, 0.13, 0.15, 0.55), (2.2, 0.12, 0.18, 0.5), (4.0, 0.11, 0.2, 0.45), (5.3, 0.09, 0.24, 0.4),
            (1.3, 0.08, 0.26, 0.4), (0, 0, 0.3, 0.5)]
    for a, reach, z, size in pads:
        c = azim(a, 0) * reach * 1.25 + Vector((0, 0, z))
        p0, _ = P.point_on(trunk, min(0.98, (z - 0.06) / 0.24))
        if reach:
            tube(W, catmull([p0, p0.lerp(c, 0.5) + Vector((0, 0, 0.02)), c], 4), lambda t: 0.008 - 0.004 * t, sides=6)
        nl = int(170 * size / 0.5)
        rx, rz = 0.085 * size / 0.5, 0.032 * size / 0.5
        for i in range(nl):
            u, v = rng.uniform(0, TAU), math.sqrt(rng.random())
            h = math.sqrt(max(0, 1 - v * v))
            p = c + Vector((math.cos(u) * v * rx * 1.2, math.sin(u) * v * rx, (h - 0.3) * rz * 1.4))
            d = azim(rng.uniform(0, TAU), rad(rng.uniform(-10, 30)) + 0.4 * h)
            ln = rng.uniform(0.018, 0.026)
            leaf(L, p, d, ln, ln * 0.55, BONSAI, nu=5, nv=3, bend=0.3, cup=0.0, fold=0.2,
                 variant=1 if h > 0.8 and rng.random() < 0.4 else 0, nvar=2)
    W.obj("wood", bark_mat("bonsai-bark", "#5f5850", 0.7, 0.2))
    L.obj("leaves", mat("bonsai-leaf", tex=col, normal=nrm, nstrength=0.3, rough=0.25))


# ================================================================ cactus column
def _cactus_texture(ribs):
    rng = np.random.default_rng(13)
    H, W = 512, 128  # one rib wide, 0.1 m tall
    u = np.linspace(0, 1, W)[None, :].repeat(H, 0)
    v = np.linspace(0, 1, H)[:, None].repeat(W, 1)
    crest = np.abs(u - 0.5) * 2  # 1 at the crest (u=0/1), 0 in the groove
    n = P.fbm(H, W, 16, 4, rng, 3, wrap_x=True)
    base = P.rgb("#4f7d5c") * (0.62 + 0.3 * crest[..., None] + 0.12 * n[..., None])
    col = base.copy()
    hgt = crest * 0.5
    for k in range(4):
        cy = (k + 0.5) / 4
        for cx in (0.0, 1.0):
            d = np.sqrt(((u - cx) * 1.0) ** 2 + ((v - cy) * 0.25) ** 2)
            dot = np.clip(1 - d / 0.07, 0, 1)
            col = col * (1 - dot[..., None]) + P.rgb("#d8d2bf") * dot[..., None]
            # radiating spines
            ang = np.arctan2((v - cy) * 0.25, (u - cx))
            rr = d
            sp = (np.abs(np.sin(ang * 5)) < 0.08) & (rr < 0.28) & (rr > 0.05)
            col[sp] = P.rgb("#e9e1c8")
            hgt = hgt + dot * 0.6
    return P.image("cactus", col), P.image("cactus-n", P.normal_from_height(hgt, 2.0), color=False)


def _ribbed(B, pts, radius, ribs=7, depth=0.28, v_rep=10.0, per_rib=8):
    """Columnar cactus stem: tube with deep rounded ribs, domed tip. UV repeats once per rib."""
    fr = P.frames(pts)
    sides = ribs * per_rib
    rows, uvs, acc = [], [], 0.0
    L = sum((b - a).length for a, b in zip(pts, pts[1:]))
    for i, (p, (t, n, b)) in enumerate(zip(pts, fr)):
        if i:
            acc += (p - pts[i - 1]).length
        tt = acc / L
        r = radius(tt)
        ring, ruv = [], []
        for k in range(sides + 1):
            a = TAU * k / sides
            prof = 1 - depth * (1 - abs(math.cos(ribs * a / 2))) ** 1.4
            ring.append(p + r * prof * (math.cos(a) * n + math.sin(a) * b))
            ruv.append((k / per_rib, acc * v_rep))
        rows.append(ring)
        uvs.append(ruv)
    B.grid(rows, uvs, flip=True)


def cactus_column():
    rng = P.rng_for("cactus")
    soil_z, _ = pot("concrete", 0.15, 0.26, r_bot=0.13, seed=121, tint="#b5b1a8", cover="gravel")
    col, nrm = _cactus_texture(7)
    B = Builder()

    def dome(r0, h_dome):
        return lambda t, r0=r0: r0 * (math.sqrt(max(0.0, 1 - max(0.0, (t - (1 - h_dome)) / h_dome) ** 2)) * 0.97 + 0.03)

    main = P.resample(catmull([(0, 0, soil_z - 0.03), (0.005, 0.0, 0.7), (-0.005, 0.005, 1.25)], 10), 0.02)
    _ribbed(B, main, dome(0.058, 0.06), ribs=7)
    for a, z0, up, out in ((0.4, 0.62, 0.36, 0.13), (3.4, 0.78, 0.26, 0.11)):
        o = azim(a, 0)
        p0 = Vector((0, 0, z0))
        arm = P.resample(catmull([p0, p0 + o * out * 0.8 + Vector((0, 0, 0.02)), p0 + o * out + Vector((0, 0, 0.1)),
                                  p0 + o * out + Vector((0, 0, up))], 8), 0.02)
        _ribbed(B, arm, dome(0.042, 0.1), ribs=7)
    B.obj("cactus", mat("cactus", tex=col, normal=nrm, nstrength=0.6, rough=0.6))


# ================================================================ manifest
def _meta(name, colors, price, materials, style, tags, placement="floor"):
    return {"name": name, "colors": colors, "price_amd": price, "materials": materials, "style": style,
            "tags": ["plant", "indoor"] + tags, "notes": f"{placement.capitalize()} plant; front faces +Z",
            "placement": placement}


PIECES = {
    "fiddle-leaf-fig-150": (fiddle_leaf_fig, _meta("Fiddle leaf fig tree, 150 cm, in woven seagrass basket",
                                                   ["green", "beige"], 48000, ["artificial foliage", "seagrass"], "boho",
                                                   ["tree", "ficus lyrata", "fiddle leaf fig", "large"])),
    "olive-tree-130": (olive_tree, _meta("Olive tree, 130 cm, in terracotta pot", ["green", "orange"], 42000,
                                         ["artificial foliage", "terracotta"], "mediterranean",
                                         ["tree", "olea europaea", "olive", "large"])),
    "monstera-100": (monstera, _meta("Monstera deliciosa, 100 cm, in matte white ceramic pot", ["green", "white"], 32000,
                                     ["artificial foliage", "ceramic"], "modern",
                                     ["monstera", "swiss cheese plant", "tropical", "large"])),
    "snake-plant-80": (snake_plant, _meta("Snake plant Laurentii, 80 cm, in concrete pot", ["green", "grey", "yellow"], 22000,
                                          ["artificial foliage", "concrete"], "modern minimalist",
                                          ["sansevieria", "snake plant", "upright"])),
    "bird-of-paradise-160": (bird_of_paradise, _meta("Bird of paradise, 160 cm, in matte black ceramic pot",
                                                     ["green", "black"], 52000, ["artificial foliage", "ceramic"], "modern",
                                                     ["strelitzia", "bird of paradise", "tropical", "large"])),
    "rubber-plant-110": (rubber_plant, _meta("Rubber plant, 110 cm, in matte white ceramic pot", ["green", "white"], 30000,
                                             ["artificial foliage", "ceramic"], "modern",
                                             ["ficus elastica", "rubber plant", "glossy"])),
    "kentia-palm-170": (kentia_palm, _meta("Kentia palm, 170 cm, in terracotta pot", ["green", "orange"], 56000,
                                           ["artificial foliage", "terracotta"], "tropical",
                                           ["palm", "howea forsteriana", "kentia", "large"])),
    "zz-plant-60": (zz_plant, _meta("ZZ plant, 60 cm, in cream ceramic pot", ["green", "white"], 18000,
                                    ["artificial foliage", "ceramic"], "modern minimalist",
                                    ["zamioculcas", "zz plant", "low light"])),
    "pothos-trailing": (pothos_trailing, _meta("Golden pothos, trailing, in small terracotta pot for a shelf",
                                               ["green", "yellow", "orange"], 9000, ["artificial foliage", "terracotta"],
                                               "boho", ["pothos", "epipremnum", "trailing", "shelf", "small"], "surface")),
    "succulent-trio": (succulent_trio, _meta("Succulent trio: echeveria, zebra haworthia and jade in mini pots",
                                             ["green", "grey", "white"], 8500, ["artificial foliage", "concrete", "ceramic",
                                                                                "terracotta"], "modern",
                                             ["succulent", "echeveria", "haworthia", "jade", "small", "set"], "surface")),
    "pampas-floor-vase": (pampas_vase, _meta("Dried pampas grass in stoneware floor vase", ["beige", "white"], 24000,
                                             ["dried grass", "stoneware"], "boho",
                                             ["pampas", "dried flowers", "vase", "tall"])),
    "ficus-bonsai": (ficus_bonsai, _meta("Ficus bonsai in glazed oval tray", ["green", "blue", "brown"], 16000,
                                         ["artificial foliage", "glazed ceramic"], "japandi",
                                         ["bonsai", "ficus retusa", "small", "tabletop"], "surface")),
    "cactus-column-125": (cactus_column, _meta("Columnar cactus, 125 cm, in concrete pot", ["green", "grey"], 26000,
                                               ["artificial foliage", "concrete"], "southwestern",
                                               ["cactus", "cereus", "columnar", "desert", "tall"])),
}
