"""Shared by the soft-goods builders: paths, the v1 texture library, the piece registry and entry records.

Credit: the entry record and the build/merge pattern follow Ashot's gap lane
(origin/experimental/floor-plans-3d:catalog/blender/gaps/common.py and build_textiles.py); the geometry comes from the
v1 bpy toolkit, vendored unchanged in ./vendor (kit, kit_cloth, kit_shapes, soft, bedding, textile, curtain_pieces).

Output (gitignored): out/<GROUP>/<slug>.glb + entries.json in catalog/ingest_extra.py's format, out/meta/<slug>.json
per built piece (merged by collect.py, so several Blender processes can build at once), out/previews/<slug>.png.
"""
import json
import subprocess
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
VENDOR = HERE / "vendor"
OUT = HERE / "out"
V1 = OUT / "v1"  # catalog/materials and the v1 soft lane's own texture sets, extracted from origin/main
GROUP = "bpy-softgoods"
MODELS = OUT / GROUP
META = OUT / "meta"
PREVIEWS = OUT / "previews"
TEX = OUT / "tex"  # textures this lane generates (runners, mats), same folder format as catalog/materials
COLORS = frozenset("black white grey beige brown red orange yellow green blue purple pink".split())


def ensure_textures(ref="origin/main"):
    """The texture library is not in v2: pull it out of the shared object store once (about 18 MB)."""
    if (V1 / "materials" / "linen" / "basecolor.jpg").exists():
        return
    V1.mkdir(parents=True, exist_ok=True)
    archive = subprocess.run(["git", "-C", str(HERE), "archive", ref, "catalog/materials", "catalog/blender/soft/tex"],
                             check=True, capture_output=True).stdout
    subprocess.run(["tar", "-x", "--strip-components=1", "-C", str(V1)], input=archive, check=True)


def setup():
    """Call inside Blender before importing builders: vendor on sys.path, kit pointed at the extracted library."""
    ensure_textures()
    sys.path[:0] = [str(VENDOR), str(HERE)]
    import kit
    kit.MATERIALS = V1 / "materials"
    return kit


REGISTRY = {}


def piece(slug, name, kind, placement, colors, price, materials, style, tags=(), notes="front faces +Z"):
    """Register a builder. colors: the BRIEF palette words ingest_extra accepts; price: whole AMD."""
    assert slug not in REGISTRY, slug
    assert colors and set(colors) <= COLORS, (slug, colors)
    assert isinstance(price, int) and price > 0, slug
    assert placement in ("floor", "surface", "wall"), slug

    def deco(fn):
        REGISTRY[slug] = (fn, dict(name=name, kind=kind, placement=placement, colors=list(colors), price=price,
                                   materials=list(materials), style=style, tags=list(tags), notes=notes,
                                   order=len(REGISTRY)))
        return fn
    return deco


def record(slug, meta, info):
    """One ingest_extra entry (Ashot's gaps/common.record shape)."""
    return dict(slug=slug, name=meta["name"], kind=meta["kind"], placement=meta["placement"], glb=f"{slug}.glb",
                size_m=info["size_m"], mesh_extents_m=info["size_m"], colors=meta["colors"], price_amd=meta["price"],
                materials=meta["materials"], style=meta["style"], license="CC0 (generated by varpet)",
                source_url="generated:bpy", notes=meta["notes"],
                tags=["generated", "bpy", "soft-goods", *meta["tags"]], tris=info["tris"], kb=info["bytes"] // 1024,
                order=meta["order"])


def write_meta(entry):
    META.mkdir(parents=True, exist_ok=True)
    (META / f"{entry['slug']}.json").write_text(json.dumps(entry, indent=1) + "\n")
