import * as THREE from 'three';
import { MotionTimeline } from './motion';
import { transitionTransform } from './transform-motion';
import type { SceneObject } from '../contracts';

let assertions = 0;
function assert(value: unknown, message: string): void { assertions++; if (!value) throw new Error(`Transform motion: ${message}`); }
const near = (a: number, b: number) => Math.abs(a - b) < 1e-7;
let now = 0;
const timeline = new MotionTimeline(() => {}, () => false, () => now);
const root = new THREE.Group(), pose = new THREE.Group(), visual = new THREE.Group();
root.add(pose); pose.add(visual); pose.matrixAutoUpdate = false;
const item: SceneObject = { id: 'chair', assetId: 'chair', name: 'Chair', position: [0, 0, 0], rotation: 0, scale: [1, 1, 1] };
const target: SceneObject = { ...item, position: [4, 0, 2], rotation: Math.PI / 2, scale: [2, 1, 0.5] };
const saved = JSON.stringify(target);
transitionTransform(timeline, root, pose, item, false);
transitionTransform(timeline, root, pose, target, true);
assert(root.position.x === 4 && root.scale.x === 2, 'root immediately reflects checked target');
const position = () => { root.updateMatrixWorld(true); return pose.getWorldPosition(new THREE.Vector3()); };
assert(near(position().x, 0), 'first presentation frame retains source position');
now = 100; timeline.update(now);
const shown = position().x;
assert(shown > 0 && shown < 4, 'intermediate frame travels toward the target');
transitionTransform(timeline, root, pose, { ...target, position: [-1, 0, 2] }, true);
assert(near(position().x, shown), 'rapid retarget preserves displayed position');
now = 500; assert(!timeline.update(now), 'settled transform returns to idle');
assert(near(position().x, -1) && pose.matrix.equals(new THREE.Matrix4()), 'final presentation matrix is exact identity');
assert(JSON.stringify(target) === saved, 'motion does not mutate document data');
transitionTransform(timeline, root, pose, { ...item, rotation: Math.PI * 179 / 180 }, false);
transitionTransform(timeline, root, pose, { ...item, rotation: -Math.PI * 179 / 180 }, true);
now = 640; timeline.update(now); root.updateMatrixWorld(true);
const facing = new THREE.Vector3(0, 0, 1).applyQuaternion(pose.getWorldQuaternion(new THREE.Quaternion()));
assert(facing.z < -0.99, 'rotation takes the short path across the wrap boundary');
timeline.finish(root);
assert(pose.matrix.equals(new THREE.Matrix4()), 'gesture takeover restores exact presentation identity');
visual.position.y = 0.1;
transitionTransform(timeline, root, pose, target, true);
now = 1000; timeline.update(now);
assert(visual.position.y === 0.1, 'placement lift has an independent visual layer');
now = 1100;
transitionTransform(timeline, root, pose, item, true);
now = 1200; timeline.update(now);
transitionTransform(timeline, root, pose, item, true);
now = 1390;
assert(!timeline.update(now), 'an unchanged scene refresh does not restart motion');
timeline.dispose();
console.log(`Transform motion checks passed (${assertions} assertions).`);
