"""Build gallery-lane framed prints headless and write their manifest.

First draw the artwork:  cd catalog && uv run python blender/gallery/gart.py
Then:  blender -b --factory-startup --python catalog/blender/gallery/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-gallery/<slug>.glb + entries.json; deletes the stale preview PNG.
Every back sits on the wall plane (max y == 0 before export = glTF back at z = -d/2).
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE), str(HERE.parent / "modernart")]
import kit  # noqa: E402
import gspecs  # noqa: E402
import parts as mparts  # noqa: E402  (modernart/parts.py: ring_sticks, quad)

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-gallery"
PREV = CATALOG / "data" / "previews-extra" / "bpy-gallery"
MET_OBJ = CATALOG / "data" / "museum-cache" / "met" / "objects"
TEX = HERE / "tex"
MAT_WHITE = "paint:#f4f2ec"
BACK = "paint:#d8cdb8"


def img_mat(slug):
    m = bpy.data.materials.new(slug)
    m.use_nodes = True
    nt = m.node_tree
    b = next(n for n in nt.nodes if n.type == "BSDF_PRINCIPLED")
    t = nt.nodes.new("ShaderNodeTexImage")
    t.image = bpy.data.images.load(str(TEX / f"{slug}.png"), check_existing=True)
    t.image.colorspace_settings.name = "sRGB"
    nt.links.new(t.outputs["Color"], b.inputs["Base Color"])
    b.inputs["Roughness"].default_value = 0.8
    b.inputs["Specular IOR Level"].default_value = 0.25
    return m


def framed(p):
    f = gspecs.FINISH[p["finish"]]
    W, H, face, D = p["w"], p["h"], p["face"], p["depth"]
    ch = 0.0015 if p["finish"] != "oak" else 0.0025
    mparts.ring_sticks(W, H, [(0, 0), (0, -D + ch), (ch, -D), (face - ch, -D), (face, -D + ch), (face, 0)],
                       0.0, H / 2, f["spec"], f["tint"], f["rough"], "frame")
    y_front = -D + 0.005          # mat / art face sits 5 mm behind the frame face
    iw, ih = W - 2 * face, H - 2 * face
    if p["mat"]:
        m, t = p["mat"], 0.003
        mparts.ring_sticks(iw, ih, [(0, y_front + t), (0, y_front), (m - t, y_front), (m, y_front + t)],
                           0.0, H / 2, MAT_WHITE, None, 0.9, "mat")
        y_art = y_front + t + 0.0005
    else:
        y_art = y_front
    aw, ah = gspecs.art_size_m(p)
    mparts.quad(-aw / 2, aw / 2, H / 2 - ah / 2, H / 2 + ah / 2, y_art, img_mat(p["slug"]))
    kit.box((iw + 0.004, 0.004, ih + 0.004), (0.0, -0.002, H / 2 - ih / 2 - 0.002), BACK, bevel=0)


def max_y():
    bpy.context.view_layer.update()
    return max((o.matrix_world @ v.co).y for o in kit.meshes() for v in o.data.vertices)


def provenance(p):
    if p["gen"] != "met":
        return {"source_url": "generated:bpy", "license": "CC0 (generated by varpet)"}
    o = json.loads((MET_OBJ / f"{p['var']}.json").read_text())
    who = o.get("artistDisplayName") or o.get("culture") or "Unknown artist"
    return {"source_url": o.get("objectURL") or f"{gspecs.MET}{p['var']}",
            "license": "CC0 (The Met Open Access)",
            "attribution": ", ".join(x for x in (who, o.get("objectDate"), "The Metropolitan Museum of Art") if x)}


def entry(p, info):
    f = gspecs.FINISH[p["finish"]]
    colors = list(dict.fromkeys(p["colors"] + [f["color"]]))
    tags = ["gallery", f["tag"], p["size"], p["family"], "landscape" if p["landscape"] else "portrait",
            "framed", "print", "wall art", "generated" if p["gen"] != "met" else "museum", "bpy"]
    if p["mat"]:
        tags.append("mat")
    return {
        "slug": p["slug"], "name": p["name"], "kind": "wall_art", "placement": "wall",
        "glb": f"{p['slug']}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
        "colors": colors, "price_amd": p["price"], "materials": [f["material"], "paper"],
        "style": gspecs.FAMILY_STYLE[p["family"]], **provenance(p),
        "notes": "Wall-hung; front faces +Z", "tags": tags,
    }


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = [p["slug"] for p in gspecs.P] if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        p = gspecs.BY_SLUG[slug]
        kit.reset()
        framed(p)
        back = max_y()
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = entry(p, info)
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        flag = "" if abs(back) <= 1e-4 else f" BACK-OFF-WALL-PLANE {back * 1000:.1f} mm"
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}{flag}", flush=True)
    order = [p["slug"] for p in gspecs.P if p["slug"] in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
