"""Build wall2-lane pieces headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/wall2/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-wall2/<slug>.glb + entries.json; deletes the stale preview PNG.
Checks the wall plane: nothing at y > 0 and a real flat back (face area on y = 0) before export.
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE)]
import kit  # noqa: E402
import kit_shapes as ks  # noqa: E402
import parts  # noqa: E402
import pieces  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-wall2"
PREV = CATALOG / "data" / "previews-extra" / "bpy-wall2"


def wall_check():
    """(max y over all verts, area in cm^2 of faces lying on y = 0)."""
    bpy.context.view_layer.update()
    top, area = -1.0, 0.0
    for o in kit.meshes():
        mw = o.matrix_world
        ys = [(mw @ v.co).y for v in o.data.vertices]
        top = max(top, max(ys))
        for p in o.data.polygons:
            if all(abs(ys[i]) < 1e-4 for i in p.vertices):
                area += p.area * mw.to_scale()[0] * mw.to_scale()[2]
    return top, area * 1e4


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(pieces.REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = pieces.REGISTRY[slug]
        kit.reset()
        parts.clear()
        parts.custom_names.clear()
        fn()
        top, area = wall_check()
        ks.shrink_images(512)
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": "wall",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "Wall-hung; front faces +Z",
            "tags": ["generated", "bpy", "wall", *meta["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        flag = "" if abs(top) <= 1e-4 and area > 10 else f" WALL-PLANE-FAIL top={top * 1000:.2f}mm"
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024} "
              f"back_cm2={area:.0f}{flag}", flush=True)
    order = [s for s in pieces.REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
