// Real-scene repro for the max-side boundary clamp miss (project_O1z9NLOylyb5kFX4).
// Auto slab polygon derives from wall centerlines, putting wall samples exactly on
// the polygon boundary — the shape that exposed ray-cast side dependence.
export const wallPlaneTopBoundaryRepro = {
  building_rr4rx7weux2fpdbh: {
    id: 'building_rr4rx7weux2fpdbh',
    type: 'building',
    object: 'node',
    visible: true,
    children: ['level_pomuk0sbwec15mf3', 'level_5msog1z8hy2lyvxr'],
    metadata: {},
    parentId: null,
    position: [0, 0, 0],
    rotation: [0, 0, 0],
  },
  level_pomuk0sbwec15mf3: {
    id: 'level_pomuk0sbwec15mf3',
    type: 'level',
    level: 0,
    height: 2.7,
    object: 'node',
    visible: true,
    children: ['wall_39bnnq29h824ryy0', 'wall_on4rj410n69n3rzf'],
    metadata: {},
    parentId: null,
  },
  level_5msog1z8hy2lyvxr: {
    id: 'level_5msog1z8hy2lyvxr',
    type: 'level',
    level: 1,
    height: 2.5,
    object: 'node',
    visible: true,
    children: ['slab_j3i4ebjg4nsu8xk7'],
    metadata: {},
    parentId: 'building_rr4rx7weux2fpdbh',
  },
  wall_39bnnq29h824ryy0: {
    id: 'wall_39bnnq29h824ryy0',
    end: [-1, 4],
    name: 'Wall 1',
    type: 'wall',
    start: [3, 4],
    object: 'node',
    visible: true,
    backSide: 'exterior',
    children: [],
    metadata: {},
    parentId: 'level_pomuk0sbwec15mf3',
    frontSide: 'interior',
  },
  wall_on4rj410n69n3rzf: {
    id: 'wall_on4rj410n69n3rzf',
    end: [-1, -1],
    name: 'Wall 2',
    type: 'wall',
    start: [-1, 4],
    object: 'node',
    visible: true,
    backSide: 'exterior',
    children: [],
    metadata: {},
    parentId: 'level_pomuk0sbwec15mf3',
    frontSide: 'interior',
  },
  slab_j3i4ebjg4nsu8xk7: {
    id: 'slab_j3i4ebjg4nsu8xk7',
    name: 'Room 1 Slab',
    type: 'slab',
    holes: [],
    object: 'node',
    polygon: [
      [-1, 4],
      [-1, -1],
      [4, -1],
      [4, 1],
      [3, 1],
      [3, 4],
    ],
    visible: true,
    metadata: {},
    parentId: 'level_5msog1z8hy2lyvxr',
    recessed: false,
    elevation: 0.19757210573188194,
    thickness: 0.5,
    holeMetadata: [],
    autoFromWalls: true,
  },
}
