"""Contemporary pieces rooted in Armenian craft for the varpet catalog (bpy, headless).

Run: textures first (cd catalog && uv run python blender/armenian/textures.py), then
     Blender -b --factory-startup --python catalog/blender/armenian/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-armenian/<slug>.glb and merges entries.json by slug.
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
sys.path.insert(0, str(HERE.parent))
import kit  # noqa: E402
import parts as P  # noqa: E402
from pieces import PIECES  # noqa: E402

OUT = HERE.parents[1] / "data" / "extra" / "bpy-armenian"


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(PIECES) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    mf = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(mf.read_text())} if mf.exists() else {}
    for slug in slugs:
        fn, meta = PIECES[slug]
        kit.reset()
        P._mats.clear()
        fn()
        # keep painted / printed / carved maps at 1k, shrink library finishes
        keep = {f"{n}.png" for n in meta.get("keep", ())}
        for img in bpy.data.images:
            if Path(img.filepath).name not in keep and img.size[0] > meta.get("px", 512):
                img.scale(meta.get("px", 512), max(1, int(img.size[1] * meta.get("px", 512) / img.size[0])))
        res = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {"slug": slug, "name": meta["name"], "kind": meta["kind"],
                         "source_url": "generated:bpy", "license": "CC0 (generated by varpet)", "glb": f"{slug}.glb",
                         "size_m": res["size_m"], "mesh_extents_m": res["size_m"],
                         **{k: meta[k] for k in ("colors", "price_amd", "materials", "style", "placement", "tags")},
                         "notes": meta["notes"], "tris": res["tris"], "bytes": res["bytes"]}
        print(f"BUILT {slug} size={res['size_m']} tris={res['tris']} kb={res['bytes'] // 1024}", flush=True)
    order = list(PIECES)
    out = sorted(entries.values(), key=lambda e: order.index(e["slug"]) if e["slug"] in order else 999)
    mf.write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n")


main()
