"""Build modern-art lane pieces headless and merge their manifest entries.

First draw the artwork:  cd catalog && uv run python blender/modernart/art.py
Then:  blender -b --factory-startup --python catalog/blender/modernart/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-modernart/<slug>.glb + entries.json; deletes the stale preview PNG.
Checks every back sits on the wall plane (max y == 0 before export = glTF back at z = -d/2).
"""
import json
import sys
from pathlib import Path

import bpy

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE)]
import kit  # noqa: E402
import parts  # noqa: E402
import specs  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-modernart"
PREV = CATALOG / "data" / "previews-extra" / "bpy-modernart"


def max_y():
    bpy.context.view_layer.update()
    return max((o.matrix_world @ v.co).y for o in kit.meshes() for v in o.data.vertices)


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = [p["slug"] for p in specs.P] if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        p = specs.BY_SLUG[slug]
        kit.reset()
        for i, it in enumerate(p["items"]):
            (parts.frame_item if it["mount"] == "frame" else parts.canvas_item)(it, specs.tex_name(slug, i))
        back = max_y()
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": p["name"], "kind": "wall_art", "placement": "wall",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": p["colors"], "price_amd": p["price"], "materials": p["materials"],
            "style": p["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "Wall-hung; front faces +Z",
            "tags": ["generated", "bpy", "wall art", "original artwork", p["style"], *p["tags"]],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        flag = "" if abs(back) <= 1e-4 else f" BACK-OFF-WALL-PLANE {back * 1000:.1f} mm"
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}{flag}", flush=True)
    order = [p["slug"] for p in specs.P if p["slug"] in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
