"""nursery2 lane helpers: reuse nursery/common.py geometry (read-only), own output paths, export, manifest.

Pieces are Z-up, metres, FRONT facing -Y.
"""
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent))
sys.path.insert(0, str(HERE.parent / "nursery"))
import kit  # noqa: E402
import kit_shapes as ks  # noqa: E402
import common as N  # noqa: E402  (nursery lane helpers: rounded_block, revolve, extrude_*, vbox, hbox)

import bmesh  # noqa: E402
import bpy  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-nursery2"
PARTS = OUT / "_parts"

OAT_BOUCLE = ("boucle", "#e6dccb")
OAT_LINEN = ("linen-alt", "#d9cfbd")
OAK = ("oak-rift", "#caa77c")
BIRCH = ("ash-light", "#e2cda9")
FELT_OAT = ("wool-felt", "#d8cdb9")
WHITE = "paint:#eeebe4"


def cyl_uv(obj, tile):
    """Cylindrical UVs in metres around Z (weave runs round the basket, no cube-projection seams)."""
    me = obj.data
    uv = me.uv_layers.active.data
    for poly in me.polygons:
        us = []
        for li in poly.loop_indices:
            co = me.vertices[me.loops[li].vertex_index].co
            us.append([math.atan2(co.y, co.x), math.hypot(co.x, co.y), co.z])
        ths = [u[0] for u in us]
        if max(ths) - min(ths) > math.pi:
            for u in us:
                if u[0] < 0:
                    u[0] += 2 * math.pi
        for li, (th, r, z) in zip(poly.loop_indices, us):
            uv[li].uv = (th * 0.3 / tile, (z + (0.3 - r) * 0.5) / tile)


def tube(points, r, spec, tint=None, roughness=None):
    """Round tube along a polyline; smooth the corners by passing arc points."""
    return kit.curve_tube(points, r, spec, tint, roughness=roughness)


def arc(c, r, a0, a1, plane="xz", n=10, fixed=0.0):
    """Arc points around centre c (2D) in a plane, the third coordinate = fixed."""
    pts = []
    for i in range(n + 1):
        a = math.radians(a0 + (a1 - a0) * i / n)
        u, v = c[0] + r * math.cos(a), c[1] + r * math.sin(a)
        pts.append({"xz": (u, fixed, v), "yz": (fixed, u, v), "xy": (u, v, fixed)}[plane])
    return pts


def wheel(r, w, at, tyre="paint:#2d2b29", hub="paint:#d9d4ca", axis="x"):
    """Wheel with a soft tyre (torus-like revolve) and hub, axle along X, `at` = wheel centre."""
    prof = []
    rr = w / 2
    for i in range(17):
        a = -math.pi / 2 + math.pi * i / 16
        prof.append((r - rr + rr * math.cos(a), rr * math.sin(a)))
    prof = [(r * 0.62, -w * 0.42)] + prof + [(r * 0.62, w * 0.42)]
    t = N.revolve(prof, (0, 0, 0), tyre, steps=32, cap_top=False, cap_bottom=False, name="tyre", finish=False)
    kit.finish(t, tyre)
    h = kit.cylinder(r * 0.64, w * 0.8, (0, 0, -w * 0.4), hub, verts=32, bevel=0.003)
    for o in (t, h):
        o.rotation_euler = (0, math.radians(90), 0) if axis == "x" else (math.radians(90), 0, 0)
        o.location = at
    return t, h


def export(slug, small=("wool-felt", "boucle", "rattan", "linen-alt", "linen")):
    N.shrink(small)
    ks.shrink_images(768)
    N.apply_modifiers()
    for o in kit.meshes():
        if not o.data.uv_layers:
            o.data.uv_layers.new(name="UVMap")
    info = kit.export(OUT / f"{slug}.glb", name=slug)
    print(f"EXPORTED {slug} size={info['size_m']} tris={info['tris']} MB={info['bytes'] / 1e6:.2f}", flush=True)
    return info


def entry(v, info):
    return {
        "slug": v["slug"], "name": v["name"], "kind": v["kind"], "placement": v.get("placement", "floor"),
        "source_url": "generated:bpy", "license": "CC0 (generated by varpet)",
        "glb": f"{v['slug']}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
        "colors": v["colors"], "price_amd": int(v["price"]), "materials": v["materials"], "style": v["style"],
        "notes": v.get("notes", "front faces +Z"), "tags": v["tags"], "tris": info["tris"], "bytes": info["bytes"],
    }


def run(family, variants, builders):
    """Build the requested slugs (all when none given) and merge into the family's manifest fragment."""
    want = set(sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else [])
    f = PARTS / f"{family}.json"
    old = {e["slug"]: e for e in json.loads(f.read_text())} if f.exists() else {}
    for v in variants:
        if want and v["slug"] not in want:
            continue
        kit.reset()
        builders[v["build"]](v)
        old[v["slug"]] = entry(v, export(v["slug"]))
    PARTS.mkdir(parents=True, exist_ok=True)
    f.write_text(json.dumps([old[v["slug"]] for v in variants if v["slug"] in old], indent=1))


def rod(p0, p1, r, spec, tint=None, verts=20, r1=None):
    """Round wooden/metal rod from point p0 to p1 (grain along its length). r1 tapers the far end."""
    from mathutils import Vector
    a, b = Vector(p0), Vector(p1)
    d = b - a
    o = kit.cylinder(r, d.length, (0, 0, 0), spec, tint, radius_top=r1, verts=verts, bevel=0.0)
    o.rotation_mode = "QUATERNION"
    o.rotation_quaternion = d.normalized().to_track_quat("Z", "Y")
    o.location = a
    return o


def sheet(path_fn, width_fn, nu, nv, spec, tint=None, thick=0.012, dish=0.0, name="sheet"):
    """Fabric surface: path_fn(t) -> (y, z) centre line, width_fn(t) -> width along X, dished edges.
    Solidified by `thick`; UVs by arc length (metres / tile) so the weave does not smear."""
    import bmesh as bm_
    m, tile = kit.material(spec, tint)
    bm = bm_.new()
    rows, s = [], 0.0
    prev = None
    for j in range(nv + 1):
        t = j / nv
        y, z = path_fn(t)
        if prev:
            s += math.hypot(y - prev[0], z - prev[1])
        prev = (y, z)
        w = width_fn(t)
        row = []
        for i in range(nu + 1):
            u = i / nu - 0.5
            row.append((bm.verts.new((u * w, y, z + dish * (2 * u) ** 2)), u * w, s))
        rows.append(row)
    uvl = bm.loops.layers.uv.new("UVMap")
    tile = tile or 1.0
    for j in range(nv):
        for i in range(nu):
            q = (rows[j][i], rows[j][i + 1], rows[j + 1][i + 1], rows[j + 1][i])
            f = bm.faces.new([c[0] for c in q])
            for loop, c in zip(f.loops, q):
                loop[uvl].uv = (c[1] / tile, c[2] / tile)
    bm_.ops.recalc_face_normals(bm, faces=bm.faces)
    obj = N._obj(bm, name)
    sol = obj.modifiers.new("t", "SOLIDIFY")
    sol.thickness = thick
    sol.offset = 0
    obj.data.materials.append(m)
    for p in obj.data.polygons:
        p.use_smooth = True
    return obj
