import '../core/renovation-check';
import { measuredShell, tracedShell, mergeReconstruction, reconstructionDifferences, type MeasuredRoom, polygonArea } from './reconstruction';
import { validateScene } from '../core/validation';
import { projectReport, projectSchedule } from './handoff';
import type { EvidenceSource } from '../contracts';

let assertions = 0;
function assert(condition: unknown, description: string): asserts condition { assertions++; if (!condition) throw new Error(`Reconstruction: ${description}`); }
function throws(action: () => unknown, description: string) { let thrown = false; try { action(); } catch { thrown = true; } assert(thrown, description); }
const room: MeasuredRoom = { name: 'Main room', x: 0, z: 0, width: 5, depth: 4, elevation: 0, ceilingHeight: 2.7, zone: 'interior' };
const measured = measuredShell('Survey', [room, { ...room, name: 'Balcony', x: 5, width: 2, zone: 'balcony', elevation: 0.1 }], 0.16, true);
assert(validateScene(measured, []).ok, 'adjacent measured rooms form valid project');
assert(measured.rooms.length === 2 && measured.walls.length === 7, 'shared edge produces one wall');
assert(measured.project?.metadata[measured.rooms[1]!.id]?.zone === 'balcony', 'balcony remains explicit');
assert(measured.project?.metadata[measured.rooms[1]!.id]?.elevation === 0.1, 'raised balcony elevation retained');
assert(Object.values(measured.project!.metadata).filter(m => m.boundary === 'interior').length === 1, 'shared wall is interior');
assert(measured.project!.assumptions.some(a => a.status === 'measured'), 'site measurements retain their status and source');
assert(measured.project!.assumptions.filter(a => a.property === 'structuralRole').every(a => a.status === 'unresolved'), 'measurements do not establish structural roles');
throws(() => measuredShell('Overlapping', [room, { ...room, x: 1 }], 0.16, false), 'overlapping rooms rejected');
throws(() => measuredShell('Invalid', [{ ...room, width: NaN }], 0.16, false), 'invalid dimensions rejected');
const source: EvidenceSource = { id: 'plan', name: 'Calibration plan', kind: 'plan', calibration: { metres: 5, pixels: 500, origin: [0, 0], rotation: 0 } };
const traced = tracedShell({ name: 'Traced', source, outline: [[0, 0], [500, 0], [500, 400], [0, 400]], partitions: [[[250, 0], [250, 400]]], pixelsPerMetre: 100, origin: [0, 0], height: 2.7, thickness: 0.16 });
assert(validateScene(traced, []).ok, 'calibrated plan with partition validates');
assert(traced.rooms.length === 2 && traced.walls.length === 7, 'T junctions close into two independent room faces');
assert(Math.abs(traced.rooms.reduce((sum, r) => sum + polygonArea(r.polygon), 0) - 20) < 1e-4, 'calibrated total area is preserved, without overlapping room floors');
assert(traced.project!.sources[0]?.calibration?.metres === 5, 'scale evidence is retained');
assert(Object.values(traced.project!.metadata).filter(m => m.boundary === 'interior').length === 1, 'traced internal partition is not marked exterior');
const precise = tracedShell({ name: 'Precise junction', source, outline: [[0,0],[1000,0],[1000,1000],[0,1000]], partitions: [[[333.33,0],[333.33,1000]]], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 });
assert(precise.rooms.length === 2 && validateScene(precise, []).ok, 'non-round junctions share exact endpoints and close rooms');
const spur = tracedShell({ name: 'Partial divider', source, outline: [[0,0],[1000,0],[1000,1000],[0,1000]], partitions: [[[500,0],[500,400]]], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 });
assert(spur.rooms.length === 1 && validateScene(spur, []).ok && polygonArea(spur.rooms[0]!.polygon) === 100, 'partial partitions do not create degenerate floor backtracking');
throws(() => tracedShell({ name: 'Island', source, outline: [[0,0],[1000,0],[1000,1000],[0,1000]], partitions: [[[300,300],[700,300]],[[700,300],[700,700]],[[700,700],[300,700]],[[300,700],[300,300]]], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 }), 'unsupported floor holes rejected rather than double-counted');
const levels = measuredShell('Levels', [{...room,elevation:1,ceilingHeight:2.5},{...room,x:5,elevation:0,ceilingHeight:2.7}],0.16,false);
const shared = levels.walls.find(w => levels.project!.metadata[w.id]?.boundary === 'interior')!;
assert(levels.project!.metadata[shared.id]?.elevation === 0 && shared.height === 3.5, 'shared wall spans the union of adjacent floor and ceiling elevations');
throws(() => tracedShell({ name: 'Bad', source, outline: [[0,0],[500,400],[500,0],[0,400]], partitions: [], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 }), 'self crossing perimeter rejected');
throws(() => tracedShell({ name: 'Bad', source, outline: [[0,0],[500,0],[500,400],[0,400]], partitions: [[[250,0],[250,600]]], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 }), 'partition outside perimeter rejected');
throws(() => tracedShell({ name: 'Near boundary', source, outline: [[0,0],[1000,0],[1000,1000],[0,1000]], partitions: [[[100,-5],[900,-5]]], pixelsPerMetre: 100, origin: [0,0], height: 2.7, thickness: 0.16 }), 'boundary tolerance uses perpendicular distance and rejects a wall five centimetres outside');
const next = structuredClone(traced); next.walls[0]!.height = 2.8;
const differences = reconstructionDifferences(traced, next);
assert(differences.length === 1 && differences[0]?.action === 'update', 'reconstruction diff isolates changed geometry');
const rejected = mergeReconstruction(traced, next, new Set());
assert(rejected.walls[0]?.height === 2.7, 'unselected inferred replacement preserves human geometry');
const accepted = mergeReconstruction(traced, next, new Set([next.walls[0]!.id]));
assert(accepted.walls[0]?.height === 2.8, 'selected replacement applies geometry');
assert(accepted.project!.assumptions.filter(a => a.entityId === next.walls[0]!.id).every(a => a.status === 'stale'), 'changed geometry invalidates existing assertions');
assert(validateScene(accepted, []).ok, 'merged project with original evidence still validates');
const exportScene = structuredClone(traced); exportScene.name = '<script>alert(1)</script>'; exportScene.rooms[0]!.name = '=SUM(1,2)';
assert(projectReport(exportScene, []).includes('&lt;script&gt;'), 'report escapes untrusted names');
assert(!projectReport(exportScene, []).includes('<script>'), 'report contains no injected executable markup');
assert(projectSchedule(exportScene, []).includes("'=SUM(1,2)"), 'spreadsheet formula injection neutralized');
console.log(`Reconstruction and handoff checks passed (${assertions} assertions).`);
