"""Build living-tables-lane pieces headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/living-tables/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-living-tables/<slug>.glb + entries.json; deletes the stale preview PNG so
render_previews.py re-renders it.
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE)]
import kit  # noqa: E402
import parts  # noqa: E402
import pieces  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-living-tables"
PREV = CATALOG / "data" / "previews-extra" / "bpy-living-tables"


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(pieces.REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = pieces.REGISTRY[slug]
        kit.reset()
        fn()
        parts.bake_modifiers()
        info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": "floor",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": meta.get("notes", "front faces +Z"), "tags": ["generated", "bpy", "living-tables", *meta.get("tags", [])],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}", flush=True)
    order = [s for s in pieces.REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
