"""Build deco-lane pieces headless and merge their manifest entries.

blender -b --factory-startup --python catalog/blender/deco/build.py -- [slug ...|all]
Writes catalog/data/extra/bpy-deco/<slug>.glb + entries.json and deletes the stale preview PNG.
Textures: run `uv run python blender/deco/tex.py` from catalog/ first (writes blender/deco/tex/).
"""
import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path[:0] = [str(HERE.parent), str(HERE)]
import bpy  # noqa: E402
import kit  # noqa: E402
import kit_shapes  # noqa: E402
import soft  # noqa: E402
import seating  # noqa: E402,F401  (registers pieces)
import casegoods  # noqa: E402,F401
from decoparts import REGISTRY  # noqa: E402

CATALOG = HERE.parents[1]
OUT = CATALOG / "data" / "extra" / "bpy-deco"
PREV = CATALOG / "data" / "previews-extra" / "bpy-deco"


def main():
    args = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv else []
    slugs = list(REGISTRY) if not args or args == ["all"] else args
    OUT.mkdir(parents=True, exist_ok=True)
    manifest = OUT / "entries.json"
    entries = {e["slug"]: e for e in json.loads(manifest.read_text())} if manifest.exists() else {}
    for slug in slugs:
        fn, meta = REGISTRY[slug]
        kit.reset()
        fn()
        soft.bake_modifiers()
        if len(bpy.data.images) > 9:  # more than 3 textured sets would break the 3 MB budget
            kit_shapes.shrink_images(512)
        info = kit.export(OUT / f"{slug}.glb", slug)
        if info["bytes"] > 2_900_000:  # over budget: halve the textures and export again
            kit_shapes.shrink_images(512)
            info = kit.export(OUT / f"{slug}.glb", slug)
        entries[slug] = {
            "slug": slug, "name": meta["name"], "kind": meta["kind"], "placement": "floor",
            "glb": f"{slug}.glb", "size_m": info["size_m"], "mesh_extents_m": info["size_m"],
            "colors": meta["colors"], "price_amd": meta["price"], "materials": meta["materials"],
            "style": meta["style"], "license": "CC0 (generated by varpet)", "source_url": "generated:bpy",
            "notes": "front faces +Z", "tags": ["generated", "bpy", "deco", *meta.get("tags", [])],
        }
        (PREV / f"{slug}.png").unlink(missing_ok=True)
        print(f"BUILT {slug} size={info['size_m']} tris={info['tris']} kb={info['bytes'] // 1024}", flush=True)
    order = [s for s in REGISTRY if s in entries]
    manifest.write_text(json.dumps([entries[s] for s in order], indent=1) + "\n")


main()
