export const SCENE_DESIGN_GUIDANCE = [
  'Scene design workflow:',
  '  - Use meters. X/Z are horizontal floor-plan axes; Y is vertical.',
  '  - Read `pascal://agent/guide` when you need construction rules; do not inspect repository code for ordinary scene editing.',
  '  - Door default: 0.9m wide by 2.1m high, floor-mounted.',
  '  - Window default: 1.5m wide by 1.5m high with a 0.9m sill height.',
  '  - For clear concrete requests, act with reasonable defaults instead of asking for clarification.',
  '  - For full homes/apartments, include realistic support spaces: kitchen, living/dining, bathrooms, hallway/entry, storage/laundry where appropriate.',
  '  - For multi-story buildings, create separate level-owned story shells. Do not stretch first-floor exterior walls to cover upper floors.',
  '  - Treat requested story count as occupied stories, not raw level count; dedicated roof/support levels are allowed and must not be deleted just to match a story count.',
  '',
  'Preferred phased tool workflow:',
  '  - Query first with list_levels, get_level_summary, get_walls, or get_zones when editing an existing scene.',
  '  - Create visible massing early: create_level as needed, then create_story_shell once per story.',
  '  - For rooms, prefer create_room, then add_door/add_window, then furnish_room.',
  '  - For stairs between floors, prefer create_stair_between_levels so slab/ceiling openings stay rectangular and do not duplicate auto-generated holes.',
  '  - For roofs, prefer create_roof and let it create/use a dedicated roof level above the top occupied story so solo/exploded level views can isolate the roof.',
  '  - verify_scene reports both levelCount and occupiedStoryCount. Use occupiedStoryCount when checking whether a one-story/two-story brief was satisfied.',
  '  - add_door/add_window use t = 0..1 along a wall: 0 is start, 0.5 is center, 1 is end.',
  '  - Use search_assets before place_item when placing a specific catalog item.',
  '  - Use apply_patch for precise bulk edits that the semantic tools cannot express.',
  '  - After each major phase, call get_level_summary or pascal://scene/current/summary so progress is visible and errors are easier to localize.',
  '  - After multi-room or full-floor work, call validate_scene and verify_scene, then fix reported issues before finishing.',
].join('\n')
